import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation function
const t = (language: Language, key: string, params?: Record<string, string | number>): string => {
  const translations = getTranslations(language);
  let text = translations[key];
  
  // If translation doesn't exist, return the key
  if (text === undefined) {
    return key;
  }
  
  // If translation is empty string, return empty string (don't fall back to key)
  if (text === '') {
    return '';
  }
  
  if (params) {
    Object.entries(params).forEach(([param, value]) => {
      text = text.replace(new RegExp(`{{${param}}}`, 'g'), value.toString());
    });
  }
  
  return text;
};

// Import translation files
const getTranslations = (language: Language): Record<string, string> => {
  switch (language) {
    case 'en':
      return enTranslations;
    case 'th':
      return thTranslations;
    default:
      return enTranslations;
  }
};

// English translations
const enTranslations = {
  // Navigation
  'nav.search': 'Search',
  'nav.saved': 'Saved',
  'nav.list': 'List',
  'nav.resources': 'Resources',
  'nav.messages': 'Messages',
  'nav.profile': 'Profile',
  
  // Header
  'header.notifications': 'Notifications',
  'header.logout': 'Logout',
  
  // Common
  'common.loading': 'Loading...',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.view': 'View',
  'common.close': 'Close',
  'common.submit': 'Submit',

  // Register/Signup
  'register.title': 'Create Account',
  'register.description': 'Join HotProp to start buying, selling, or renting properties',
  'register.platformNotice': 'Important: Direct Owner-to-Buyer Platform',
  'register.platformDescription': 'HotProp is exclusively for property <strong>owners</strong> and people looking to <strong>buy or rent</strong> properties. This platform connects owners directly with buyers and renters, eliminating agent fees and commissions.',
  'register.firstName': 'First Name',
  'register.lastName': 'Last Name',
  'register.email': 'Email',
  'register.phone': 'Phone (Optional)',
  'register.password': 'Password',
  'register.confirmPassword': 'Confirm Password',
  'register.firstNamePlaceholder': 'John',
  'register.lastNamePlaceholder': 'Doe',
  'register.emailPlaceholder': 'john@example.com',
  'register.phonePlaceholder': '+1 (555) 123-4567',
  'register.passwordPlaceholder': 'Create a password',
  'register.confirmPasswordPlaceholder': 'Confirm your password',
  'register.notAgentConfirm': 'I herewith confirm that I am / we are NOT a real-estate agent.',
  'register.notAgentRequired': 'Required: This platform is for property owners and seekers only',
  'register.agreeTerms': 'I agree to the',
  'register.termsOfService': 'Terms of Service',
  'register.privacyPolicy': 'Privacy Policy',
  'register.and': 'and',
  'register.createAccount': 'Create Account',
  'register.creatingAccount': 'Creating Account...',
  'register.haveAccount': 'Already have an account?',
  'register.signIn': 'Sign in',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.clear': 'Clear',
  'common.apply': 'Apply',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.ok': 'OK',
  
  // Add Listing
  'addListing.title': 'Create Listing',
  'addListing.description': 'List a property or post a requirement to connect with others',
  'addListing.listProperty': 'List Property',
  'addListing.postRequirement': 'Post Requirement',
  
  // (Property Types moved to Forms section)
  
  // Search
  'search.properties': 'Properties',
  'search.requirements': 'Requirements',
  'search.noPropertiesFound': 'No properties found',
  'search.noRequirementsFound': 'No requirements found',
  'search.propertiesFound': '{{count}} properties found',
  'search.requirementsFound': '{{count}} requirements found',
  'search.adjustCriteria': 'Try adjusting your search criteria',
  'search.startSearching': 'Start searching for properties above',
  'search.placeholder': 'Search properties, locations...',
  'search.filterButton': 'Filter',
  
  // Notifications
  'notifications.title': 'Notifications',
  'notifications.markAllRead': 'Mark all as read',
  'notifications.noNotifications': 'No notifications',
  'notifications.matches': 'Latest Matches',
  'notifications.newMatches': 'New matches found for your requirements',
  'notifications.validationReminder': 'Please confirm your listing is still available',
  'notifications.propertyReactivated': 'Property reactivated successfully',
  'notifications.requirementReactivated': 'Requirement reactivated successfully',
  'notifications.failedReactivateProperty': 'Failed to reactivate property',
  'notifications.failedReactivateRequirement': 'Failed to reactivate requirement',
  
  // Password Reset
  'forgotPassword.linkText': 'Forgot Password?',
  'forgotPassword.title': 'Forgot Password',
  'forgotPassword.description': 'Enter your email address and we\'ll send you a link to reset your password',
  'forgotPassword.email': 'Email Address',
  'forgotPassword.emailPlaceholder': 'Enter your email address',
  'forgotPassword.sendLink': 'Send Reset Link',
  'forgotPassword.sendResetEmail': 'Send Reset Link',
  'forgotPassword.backToLogin': 'Back to Login',
  'forgotPassword.successMessage': 'If an account with this email exists, you will receive a password reset email.',
  'forgotPassword.emailRequired': 'Email address is required',
  'forgotPassword.sending': 'Sending...',
  'forgotPassword.emailSent': 'Email Sent!',
  'forgotPassword.checkEmail': 'Check your email for the reset link',
  'forgotPassword.emailSentDescription': 'If an account with this email exists, you will receive a password reset email.',
  'forgotPassword.emailSentInstructions': 'Click the link in the email to reset your password. The link will expire in 1 hour.',
  'forgotPassword.error': 'Error',
  'forgotPassword.tryAgain': 'Please try again',
  
  'resetPassword.title': 'Reset Password',
  'resetPassword.description': 'Enter your new password below',
  'resetPassword.newPassword': 'New Password',
  'resetPassword.confirmPassword': 'Confirm New Password',
  'resetPassword.newPasswordPlaceholder': 'Enter new password',
  'resetPassword.passwordPlaceholder': 'Enter new password',
  'resetPassword.confirmPasswordPlaceholder': 'Confirm new password',
  'resetPassword.resetPassword': 'Reset Password',
  'resetPassword.successMessage': 'Password reset successfully! You can now log in with your new password.',
  'resetPassword.invalidToken': 'Invalid or expired reset token',
  'resetPassword.invalidTokenDescription': 'The reset link has expired or is invalid. Please request a new one.',
  'resetPassword.requestNew': 'Request New Reset Link',
  'resetPassword.passwordRequired': 'Password is required',
  'resetPassword.passwordMinLength': 'Password must be at least 8 characters',
  'resetPassword.passwordsDoNotMatch': 'Passwords do not match',
  'resetPassword.resetting': 'Resetting...',
  'resetPassword.success': 'Success!',
  'resetPassword.successDescription': 'Password reset successfully! You can now log in.',
  'resetPassword.error': 'Error',
  'resetPassword.tryAgain': 'Please try again',
  'resetPassword.backToLogin': 'Back to Login',
  
  // Common
  'common.success': 'Success!',
  'common.error': 'Error',
  
  // Matches
  'matches.title': 'Latest Matches',
  'matches.noMatches': 'No matches found',
  'matches.compatibility': '{{score}}% match',
  'matches.viewDetails': 'View Details',
  'matches.showingBuyerRequirements': 'Showing buyer requirements',
  'matches.contactDirectly': 'These buyers are looking for properties. Contact them directly to discuss opportunities!',
  
  // Forms
  'form.title': 'Title',
  'form.description': 'Description',
  'form.price': 'Price',
  'form.currency': 'Currency',
  'form.bedrooms': 'Bedrooms',
  'form.bathrooms': 'Bathrooms',
  'property.bedrooms': 'Bedrooms',
  'property.bathrooms': 'Bathrooms',
  'property.landSize': 'Land Size',
  'property.buildSize': 'Build Size',
  'property.size': 'Size',
  'property.land': 'Land',
  'property.living': 'Living',
  'property.forRent': 'For Rent',
  'property.forSale': 'For Sale',
  'form.area': 'Area',
  'form.city': 'City',
  'form.state': 'State',
  'form.country': 'Country',
  'form.amenities': 'Amenities',
  'form.required': 'This field is required',
  'form.email': 'Email',
  'form.phone': 'Phone',
  'form.propertyType': 'Property Type',
  'form.transactionType': 'Listing Type',
  'form.listingType': 'Listing Type',
  'form.lookingFor': 'Looking For',
  'form.address': 'Address',
  'form.yearBuilt': 'Year Built',
  'form.landSize': 'Land Size',
  'form.buildSize': 'Build Size',
  'form.purchase': 'Purchase',
  'form.rent': 'Rent',
  'form.rentPrice': 'Rent Price',
  'form.minPrice': 'Min Price (Optional)',
  'form.maxPrice': 'Max Price (Optional)',
  'form.purchasePriceRange': 'Purchase Price Range',
  'form.rentalPriceRange': 'Rental Price Range',
  'form.minPurchasePrice': 'Min Purchase Price',
  'form.maxPurchasePrice': 'Max Purchase Price',
  'form.minRentalPrice': 'Min Rental Price',
  'form.maxRentalPrice': 'Max Rental Price',
  'form.minBedrooms': 'Min Bedrooms',
  'form.minBathrooms': 'Min Bathrooms',
  'form.minArea': 'Min Area',
  'form.minLivingArea': 'Min. Living Area',
  'form.minLandArea': 'Min. Land Area',
  'form.maxArea': 'Max Area',
  'form.urgency': 'Urgency',
  'form.contactEmail': 'Contact Email',
  'form.contactPhone': 'Contact Phone',
  'form.areaUnit': 'Area Unit',
  'form.selectType': 'Select type',
  'form.selectCurrency': 'Select currency',
  'form.selectUnit': 'Select unit',
  'form.optional': 'Optional',
  'form.whatLookingFor': 'What are you looking for?',
  'form.describeRequirement': 'Describe your ideal property requirements',
  'form.salePriceLabel': 'Sale Price',
  'form.priceLabel': 'Price',
  'form.submit': 'Submit',
  'form.update': 'Update',
  'form.save': 'Save Property',
  'form.saveRequirement': 'Save Requirement',
  'form.savingListing': 'Please wait while we save your listing...',
  'form.addAmenity': 'Add Amenity',
  'form.addImages': 'Add Images',
  'form.uploadImages': 'Upload Images',
  'form.addMedia': 'Add Photos & Videos',
  'form.uploadMedia': 'Upload Photos & Videos',
  'form.contactPhoneOptional': 'Contact Phone (Optional)',
  'form.contactEmailLabel': 'Contact Email',
  'form.requiredAmenitiesOptional': 'Required Amenities (Optional)',
  'form.selectFromCommonAmenities': 'Select from common amenities',
  'form.landSizeUnit': 'Land Size Unit',
  'form.buildSizeUnit': 'Build Size Unit',
  'form.addNew': 'Add New',
  'form.images': 'Images',
  'form.noImagesUploaded': 'No images uploaded yet',
  'form.uploadingImages': 'Uploading images...',
  'form.remove': 'Remove',
  'form.delete': 'Delete',
  'form.deleting': 'Deleting...',
  
  // Success messages
  'success.propertyDeleted': 'Property Deleted',
  'success.propertyDeletedDesc': 'Your property has been successfully deleted.',
  'success.requirementDeleted': 'Requirement Deleted', 
  'success.requirementDeletedDesc': 'Your requirement has been successfully deleted.',
  
  // Error messages
  'error.failedToDelete': 'Failed to Delete',
  'error.tryAgain': 'Please try again later.',
  
  // Confirmation dialogs
  'confirm.deleteProperty': 'Delete Property?',
  'confirm.deletePropertyDesc': 'This action cannot be undone. Are you sure you want to delete this property permanently?',
  'confirm.deleteRequirement': 'Delete Requirement?',
  'confirm.deleteRequirementDesc': 'This action cannot be undone. Are you sure you want to delete this requirement permanently?',
  
  // Property Types
  'propertyType.house': 'House',
  'propertyType.apartment': 'Apartment',
  'propertyType.land': 'Land',
  'propertyType.townhouse': 'Townhouse',
  'propertyType.poolvilla': 'Pool Villa',
  
  // Transaction Types
  'transactionType.sell': 'For Sale',
  'transactionType.rent': 'For Rent',
  'transactionType.buy': 'For Purchase',
  'transactionType.sell_or_rent': 'For Sale and Rent',
  'transactionType.buy_or_rent': 'For Purchase and Rent',
  
  // Currencies
  'currency.USD': 'USD ($)',
  'currency.THB': 'THB (฿)',
  
  // Area Units
  'unit.sqm': 'Square Meters',
  'unit.sqw': 'Square Wah',
  'unit.sqft': 'Square Feet',
  'unit.sqmDetailed': 'Square Meters (sqm)',
  'unit.sqwDetailed': 'Square Wah (sqw)',
  
  // Urgency
  'urgency.flexible': 'Flexible',
  'urgency.normal': 'Normal',
  'urgency.urgent': 'Urgent',
  
  // Placeholders
  'placeholder.propertyTitle': 'e.g., Beautiful 3BR Villa with Pool',
  'placeholder.requirementTitle': 'e.g., 3BR House with Pool in Downtown',
  'placeholder.description': 'Describe your property or requirements...',
  'placeholder.address': 'Street address',
  'placeholder.city': 'City name',
  'placeholder.state': 'State/Province',
  'placeholder.country': 'Country',
  'placeholder.email': 'your.email@example.com',
  'placeholder.emailExample': 'your@email.com',
  'placeholder.phone': '+1234567890',
  'placeholder.phoneExample': '+1 (555) 123-4567',
  'placeholder.price': '',
  'placeholder.bedrooms': '',
  'placeholder.bathrooms': '',
  'placeholder.area': '',
  'placeholder.yearBuilt': '',
  'placeholder.selectUnit': 'Select unit',
  'placeholder.selectPropertyType': 'Select Property Type',
  'placeholder.selectListingType': 'Select Listing Type',
  'placeholder.selectCountry': 'Select country',
  'placeholder.selectState': 'Select state',
  'placeholder.selectCountryFirst': 'Select country first',
  
  // Amenities
  'amenity.carPark': 'Car Park',
  'amenity.coveredCarPark': 'Covered Car Park',
  'amenity.garden': 'Garden',
  'amenity.childrenPlayground': 'Children\'s Playground',
  'amenity.communalPool': 'Communal Pool',
  'amenity.privatePool': 'Private Pool',
  'amenity.sauna': 'Sauna',
  'amenity.gym': 'Gym',
  'amenity.nearBeach': 'Near Beach (<500mtr)',
  'amenity.nearSchool': 'Near School (<1km)',
  'amenity.nearHospital': 'Near Hospital (<1km)',
  'amenity.nearRestaurants': 'Near Restaurants (<500mtr)',
  'amenity.nearConvenience': 'Near Convenience St. (<500mtr)',
  'amenity.quietLocation': 'Quiet Location',
  'amenity.seaView': 'Sea View',
  'amenity.mountainView': 'Mountain View',
  'amenity.lakeView': 'Lake View',
  'amenity.gardenView': 'Garden View',
  'amenity.balcony': 'Balcony',
  'amenity.rooftopTerrace': 'Rooftop Terrace',
  'amenity.petsOk': 'Pets OK',
  'amenity.laundryFacilities': 'Laundry Facilities',
  'amenity.internetWifi': 'Internet WiFi',
  'amenity.security24h': '24h Security',
  
  // Form instructions
  'form.numbersOnly': '(only enter numbers)',
  
  // Premium Welcome Page
  'premium.welcomeTitle': 'Thank you very much for upgrading to Premium Membership.',
  'premium.welcomeMessage': 'Your listings will now receive a higher priority, you can list more than one property or requirement and you enjoy the other benefits of Premium Membership (we will keep adding more benefits).',
  'premium.backToHome': 'Back to Home Page',
  
  // Premium restrictions
  'premium.multipleListingsRequired': 'Premium membership required to list multiple properties. Please upgrade to continue.',
  'premium.multipleRequirementsRequired': 'Premium membership required to post multiple requirements. Please upgrade to continue.',
  
  // Languages
  'language.english': 'English',
  'language.thai': 'ไทย',
  'language.select': 'Language',
  
  // Resources
  'resources.title': 'Resources',
  'resources.description': 'Find support services and useful resources',
  'resources.serviceProviders': 'Service Providers',
  'resources.otherResources': 'Other Resources',
  'resources.serviceCategories': 'Service Categories',
  'resources.resourceCategories': 'Resource Categories',
  'resources.allServices': 'All Services',
  'resources.allResources': 'All Resources',
  'resources.noServiceProviders': 'No service providers available yet',
  'resources.noResources': 'No resources available yet',
  'resources.contactAdmin': 'Service providers are added by our team.',
  'resources.contactAdminResources': 'Resources are curated and managed exclusively by our admin team.',
  'resources.contactUs': 'Contact us',
  'resources.serviceAreas': 'Service Areas:',
  'resources.email': 'Email',
  'resources.call': 'Call {{number}}',
  'resources.download': 'Download',
  'resources.visit': 'Visit',
  'resources.visitWebsite': 'Visit Website',

  // Help page
  'help.title': 'Need Help?',
  'help.subtitle': 'We\'re here to help you with any questions or issues you may have.',
  'help.contactUs': 'Contact Support',
  'help.description': 'Choose how you\'d like to reach out to our support team.',
  'help.inAppMessage': 'In-App Message',
  'help.sendEmail': 'Send Email',
  'help.inAppTitle': 'Send us a message',
  'help.inAppDescription': 'Send a message directly through the app. You\'ll receive a response in your messages.',
  'help.yourMessage': 'Your Message',
  'help.messagePlaceholder': 'Describe your issue or question in detail...',
  'help.sending': 'Sending...',
  'help.sendMessage': 'Send Message',
  'help.emailTitle': 'Send us an email',
  'help.emailDescription': 'Send an email directly to our support team at applied.skill@gmail.com',
  'help.subject': 'Subject',
  'help.subjectPlaceholder': 'Brief description of your issue',
  'help.fromUser': 'From',
  'help.faqTitle': 'Frequently Asked Questions',
  'help.faq1Question': 'How do I list my property?',
  'help.faq1Answer': 'Click on "List Property" in the navigation and fill out the property details form.',
  'help.faq2Question': 'How do I contact property owners?',
  'help.faq2Answer': 'Click on any property listing and use the "Contact Owner" button to send a direct message.',
  'help.faq3Question': 'What are buyer requirements?',
  'help.faq3Answer': 'Buyer requirements allow you to specify what type of property you\'re looking for, and we\'ll notify you of matching listings.',
  
  // Service categories
  'serviceCategory.legal': 'Legal Services',
  'serviceCategory.legal.description': 'Contracting, property law, etc.',
  'serviceCategory.building': 'Building Services',
  'serviceCategory.building.description': 'Builders, building materials, etc.',
  'serviceCategory.architects': 'Architects',
  'serviceCategory.architects.description': 'Architectural design and planning',
  'serviceCategory.interior': 'Interior Designers',
  'serviceCategory.interior.description': 'Interior design and decoration',
  'serviceCategory.surveyors': 'Surveyors',
  'serviceCategory.surveyors.description': 'Land and property surveying',
  'serviceCategory.handymen': 'Handymen',
  'serviceCategory.handymen.description': 'General repair and maintenance',
  'serviceCategory.pool': 'Pool Cleaners',
  'serviceCategory.pool.description': 'Pool maintenance and cleaning',
  'serviceCategory.garden': 'Gardeners',
  'serviceCategory.garden.description': 'Garden and landscape maintenance',
  'serviceCategory.relocation': 'Relocation Service',
  'serviceCategory.relocation.description': 'Moving and relocation services',
  'serviceCategory.cleaning': 'Cleaning Service',
  'serviceCategory.cleaning.description': 'Professional cleaning services',
  'serviceCategory.photography': 'Prof. Photo/Video Service',
  'serviceCategory.photography.description': 'Professional photography and videography',
  'serviceCategory.other': 'Other',
  'serviceCategory.other.description': 'Other support services',
  
  // Resource categories
  'resourceCategory.documents': 'Useful Documents',
  'resourceCategory.documents.description': 'Contract templates and legal documents',
  'resourceCategory.links': 'Useful Links',
  'resourceCategory.links.description': 'Legal AI services and external resources',
  
  // Resource documents
  'resource.purchaseAgreement.title': 'Property Purchase Agreement Template',
  'resource.purchaseAgreement.description': 'Standard template for property purchase agreements in Thailand',
  'resource.rentalContract.title': 'Rental Contract Template',
  'resource.rentalContract.description': 'Comprehensive rental agreement template with Thai legal requirements',
  'resource.dueDiligence.title': 'Due Diligence Checklist',
  'resource.dueDiligence.description': 'Essential checklist for property buyers to verify legal status',
  
  // Resource links
  'resource.legalAI.title': 'Legal AI Assistant for Property Law',
  'resource.legalAI.description': 'AI-powered legal assistance for property-related questions',
  'resource.landDept.title': 'Thai Land Department Portal',
  'resource.landDept.description': 'Official government portal for land title verification',
  'resource.taxCalculator.title': 'Property Tax Calculator',
  
  // Profile page
  'profile.premium': 'Premium',
  'profile.free': 'Free',
  'profile.verified': 'Verified',
  'profile.editProfile': 'Edit Profile',
  'profile.logout': 'Logout',
  'profile.listings': 'Listings',
  'profile.saved': 'Saved',
  'profile.requests': 'Requests',
  'profile.upgradeToPremium': 'Upgrade to Premium',
  'profile.upgradeDescription': 'Get premium listings, notifications, and more',
  'profile.upgrade': 'Upgrade',
  'profile.getVerified': 'Get Verified',
  'profile.getVerifiedDescription': 'Verify your property ownership',
  'profile.verificationBenefits': 'Stand out to buyers with verified ownership status',
  'profile.verificationPending': 'Verification in progress',
  'profile.verificationPendingDesc': 'Your verification documents are being reviewed',
  'profile.verificationRejected': 'Verification was rejected',
  'profile.verificationRejectedDesc': 'Please submit new documents for verification',
  'profile.myProperties': 'My Properties',
  'profile.savedProperties': 'Saved Properties',
  'profile.myRequirements': 'My Requirements',
  'profile.myListings': 'My Listings',
  'profile.addNew': 'Add New',
  'profile.noPropertiesYet': 'You haven\'t listed any properties yet',
  'profile.createFirstListing': 'Create Your First Listing',
  'profile.noSavedYet': 'You haven\'t saved any properties yet',
  'profile.browseProperties': 'Browse Properties',
  'profile.noRequirementsYet': 'You haven\'t posted any requirements yet',
  'profile.postFirstRequirement': 'Post Your First Requirement',
  
  // Edit Profile page
  'editProfile.title': 'Edit Profile',
  'editProfile.firstName': 'First Name',
  'editProfile.lastName': 'Last Name',
  'editProfile.phoneNumber': 'Phone Number',
  'editProfile.firstNamePlaceholder': 'Enter your first name',
  'editProfile.lastNamePlaceholder': 'Enter your last name',
  'editProfile.phonePlaceholder': 'Enter your phone number',
  'editProfile.cancel': 'Cancel',
  'editProfile.saveChanges': 'Save Changes',
  'editProfile.saving': 'Saving...',
  'editProfile.firstNameRequired': 'First name is required',
  'editProfile.lastNameRequired': 'Last name is required',
  'editProfile.profileUpdated': 'Profile updated',
  'editProfile.profileUpdatedDesc': 'Your profile has been updated successfully.',
  'editProfile.updateFailed': 'Update failed',
  
  // Favorites page
  'favorites.title': 'Saved Properties',
  'favorites.subtitle': 'Properties you\'ve bookmarked',
  'favorites.noSavedTitle': 'No saved properties',
  'favorites.noSavedDescription': 'Start browsing and save properties you\'re interested in',
  
  // Premium page
  'premium.featuresTitle': 'Premium Features',
  'premium.creditCardPayment': 'Credit Card Payment',
  'premium.securePaymentSetup': 'Click the button below to set up your secure payment',
  'premium.payWithPromptPay': 'Pay with PromptPay',
  'premium.close': 'Close',
  
  // Login page
  'login.welcomeBack': 'Welcome Back',
  'login.signInToContinue': 'Sign in to your account to continue',
  'login.email': 'Email',
  'login.emailPlaceholder': 'Enter your email',
  'login.password': 'Password',
  'login.passwordPlaceholder': 'Enter your password',
  'login.signIn': 'Sign In',
  'login.signingIn': 'Signing In...',
  'login.noAccount': 'Don\'t have an account?',
  'login.signUp': 'Sign up',
  'login.termsAndPrivacy': 'By signing in, you agree to our Terms of Service and Privacy Policy',
  'login.emailNotVerified': 'Email Not Verified',
  'login.resendVerificationText': 'Your email address needs to be verified before you can sign in.',
  'login.resendVerification': 'Send Verification Email',
  'login.sendingVerification': 'Sending...',
  'login.cancelResend': 'Cancel',
  'resource.taxCalculator.description': 'Calculate property taxes and transfer fees',
  
  // Home page
  'home.premium': 'Premium',
  'home.premiumDescription': 'Boost your chances',
  'home.premiumMember': 'Premium Member',
  'home.activeSubscription': 'Active subscription',
  'home.resources': 'Resources',
  'home.resourcesDescription': 'Get support services',
  'home.admin': 'Admin',
  'home.adminPanel': 'Admin panel',
  'home.welcomeTitle1': 'Welcome to HotProp',
  'home.welcomeTitle2': 'Smart Deals, 0 Fees!',
  'home.welcomeDescription': 'Connect directly with property owners • No agent fees • Real deals',
  'home.featuredProperties': 'Featured Properties',
  'home.viewAll': 'View all',
  'home.noFeaturedProperties': 'No featured properties available',

  // Search page
  'search.iWantTo': 'I want to ...',
  'search.buy': 'Buy',
  'search.rent': 'Rent',
  'search.sell': 'Sell',
  'search.let': 'Let',
  'search.filters': 'Search Filters',
  'search.currency': 'Currency',
  'search.priceRange': 'Price Range',
  'search.maxRental': 'Max rental: {amount}/month',
  'search.maxSalePrice': 'Max sale price: {amount}',
  'search.bedrooms': 'Bedrooms',
  'search.bathrooms': 'Bathrooms',
  'search.city': 'City',
  'search.any': 'Any',
  'search.enterCity': 'Enter city',
  'search.applyFilters': 'Apply Filters',
  'search.clear': 'Clear',
  'search.clearFilters': 'Clear filters',
  'search.propertyTypes': 'Property Types',
  'search.showingBuyerRequirements': '📊 Showing buyer requirements',
  'search.buyerRequirementsDescription': 'These buyers are looking for properties. Contact them directly to discuss opportunities!',
  'search.browseRequirements': 'Browse buyer requirements to find potential customers',

  // Property and requirement cards
  'card.deactivated': 'DEACTIVATED',
  'card.premium': 'PREMIUM',
  'card.premiumOwner': 'Premium',
  'card.verifiedOwner': 'Verified Owner',
  'card.noImageAvailable': 'No image available',
  'card.hoursAgo': '{hours} hours ago',
  'card.daysAgo': '{days} days ago',
  'card.upTo': 'Up to',
  'card.from': 'From',
  'card.bed': 'bed',
  'card.bath': 'bath',
  'card.message': 'Message',
  'card.call': 'Call',
  'card.reactivateProperty': 'Reactivate Property',
  'card.reactivating': 'Reactivating...',
  'card.required': 'Required:',
  'card.more': '+{count} more',
  'card.reactivateRequirement': 'Reactivate Requirement',

  // Premium signup page
  'premium.upgradeTitle': 'Upgrade to Premium',
  'premium.premiumMember': 'Premium Member',
  'premium.choosePlan': 'Choose Your Plan',
  'premium.paymentMethod': 'Payment Method',
  'premium.continueToPayment': 'Continue to Payment',
  'premium.completePayment': 'Complete Payment',
  'premium.monthlyPremium': 'Monthly Premium',
  'premium.sixMonthPremium': '6-Month Premium',
  'premium.perMonth': 'per month',
  'premium.forSixMonths': 'for 6 months',
  'premium.save33': 'Save 33% vs monthly',
  'premium.moreFeatures': '+{count} more features',
  'premium.propertyVerification': 'Property ownership verification',
  'premium.instantNotifications': 'Instant match notifications (80%+ compatibility)',
  'premium.priceVisualization': 'Smart price trend visualization by neighborhood',
  'premium.prioritySupport': 'Priority customer support',
  'premium.advancedFilters': 'Advanced search filters',
  'premium.unlimitedListings': 'List Multiple Properties & Requirements',
  'premium.allMonthlyFeatures': 'All monthly features included',
  'premium.bestValue': 'Best value for serious users',
  'premium.promptpayTitle': 'PromptPay / QR Code',
  'premium.promptpayDesc': 'Pay instantly with your mobile banking app',
  'premium.creditCardTitle': 'Visa / MasterCard',
  'premium.creditCardDesc': 'Credit or debit card',
  'premium.twoWeeksFree': '2 weeks FREE',
  'premium.freeTrialTerms': 'Free Trial Terms:',
  'premium.freeTrialDesc': 'Get 2 weeks of Premium access completely free! Your card won\'t be charged during the trial. Cancel at least 3 days before the trial ends to avoid being charged.',
  'premium.plan': 'Plan:',
  'premium.amount': 'Amount:',
  'premium.trialPeriod': 'Trial Period:',
  'premium.creditCardInfo': 'Credit Card Information',
  'premium.processing': 'Processing...',
  'premium.startFreeTrial': 'Start 2-Week Free Trial',
  'premium.payNow': 'Pay ฿{amount} Now',
  'premium.scanQR': 'Scan QR Code to Pay',
  'premium.qrInstructions': 'Open your mobile banking app and scan this QR code to complete your payment.',
  'premium.qrExpires': 'QR Code expires in:',
  'premium.paymentComplete': 'Payment Complete!',
  'premium.activePremium': 'Your Premium subscription is now active.',
  'premium.enjoyingBenefits': 'You are currently enjoying Premium benefits!',
  'premium.activeSubscription': 'Active Subscription',
  'premium.yourPremiumBenefits': 'Your Premium Benefits',
  'premium.viewPriceTrends': 'View Price Trends',
  'premium.viewNotifications': 'View Notifications',
  'premium.cancelSubscription': 'Cancel subscription',
  
  // Toast messages
  'premium.toast.selectPaymentMethod': 'Please select a payment method',
  'premium.toast.selectPaymentDesc': 'Choose either PromptPay/QR Code or Credit Card to continue',
  'premium.toast.promptPaySuccess': 'PromptPay Payment Initiated',
  'premium.toast.promptPaySuccessDesc': 'Please complete the payment using your mobile banking app',
  'premium.toast.paymentFailed': 'Payment Failed',
  'premium.toast.paymentFailedDesc': 'Please try again or contact support',
  'premium.toast.paymentSetupFailed': 'Payment Setup Failed',
  'premium.toast.welcomeToPremium': 'Welcome to Premium!',
  'premium.toast.welcomeDesc': 'You now have 2 weeks free Premium access. You\'ll only be charged after the trial ends unless you cancel.',
  'premium.toast.subscriptionSetupFailed': 'Subscription Setup Failed',
  'premium.toast.contactSupport': 'Please contact support',
  'premium.toast.subscriptionCancelled': 'Subscription Cancelled',
  'premium.toast.downgradedDesc': 'You have been downgraded to Regular Subscriber. Your premium access will continue until the end of your current billing period.',
  'premium.toast.downgradeFailed': 'Downgrade Failed',
  
  // QR modal additional keys
  'premium.instructions': 'Instructions:',
  'premium.confirmPayment': 'Confirm the payment',
  'premium.activateAccess': 'Your Premium access will be activated',
  'premium.promptpayPayment': 'PromptPay Payment',
  'premium.generateQRCode': 'Generate QR Code',
  'premium.setUpPayment': 'Set Up Payment',
  'premium.paymentId': 'Payment ID:',
  
  // Messages page
  'messages.title': 'Messages',
  'messages.searchConversations': 'Search conversations...',
  'messages.noConversations': 'No conversations yet',
  'messages.startMessaging': 'Start messaging property owners or buyers',
  'messages.propertyInquiry': 'Property inquiry',
  'messages.generalMessage': 'General message',
  'messages.property': 'Property',
  'messages.message': 'Message',
  'messages.inactive': 'Inactive',
  'messages.conversation': 'Conversation',
  'messages.typeMessage': 'Type your message...',
  'messages.new': 'New',
  'messages.unknownUser': 'Unknown User',
  'messages.failedToSend': 'Failed to send message',
  
  // Notifications page - additional to existing
  'notifications.new': 'new',
  'notifications.allCaughtUp': 'You\'re all caught up! New notifications will appear here.',
  'notifications.reactivate': 'Reactivate',
  'notifications.reactivating': 'Reactivating...',
  'notifications.success': 'Success!',
  'notifications.error': 'Error',
  'notifications.reactivated': 'reactivated successfully',
  'notifications.markedAsRead': 'Notification marked as read',
  'notifications.allMarkedAsRead': 'All notifications marked as read',
  'notifications.deleted': 'Notification deleted',
  'notifications.failedMarkAsRead': 'Failed to mark notification as read',
  'notifications.failedMarkAllAsRead': 'Failed to mark all notifications as read',
  'notifications.failedDelete': 'Failed to delete notification',
  'notifications.minAgo': '{minutes}m ago',
  'notifications.hourAgo': '{hours}h ago',
  'notifications.dayAgo': '{days}d ago',
  
  // Property Details
  'propertyDetails.description': 'Property Description',
  'propertyDetails.amenities': 'Amenities',
  'propertyDetails.details': 'Property Details',
  'propertyDetails.listedBy': 'Listed by Owner',
  'propertyDetails.propertyType': 'Property Type',
  'propertyDetails.yearBuilt': 'Year Built',
  'propertyDetails.listed': 'Listed',
  'propertyDetails.reportListing': 'Report this listing',
  'propertyDetails.rating': 'rating',
  'propertyDetails.call': 'Call',
  'propertyDetails.email': 'Email',
  'propertyDetails.sendMessage': 'Send Message',
  'propertyDetails.share': 'Share',
  'propertyDetails.back': 'Back',
  'propertyDetails.addToFavorites': 'Add to Favorites',
  'propertyDetails.removeFromFavorites': 'Remove from Favorites',
  
  // Additional amenities
  'amenity.doubleCarPark': 'Double Car Park',
  'amenity.poolSpecific': 'Pool 6*3mtrs',
  'amenity.balconyWithSeaview': 'Balcony with Seaview',
  'amenity.fullyFurnished': 'Fully furnished',
  'amenity.openChimney': 'Open Chimney',
  'amenity.privateBar': 'Private Bar',
  
  // Legacy amenity names for backward compatibility
  'amenities.pool': 'Swimming Pool',
  'amenities.gym': 'Gym',
  'amenities.parking': 'Parking',
  'amenities.security': '24/7 Security',
  'amenities.elevator': 'Elevator',
  'amenities.balcony': 'Balcony',
  'amenities.garden': 'Garden',
  'amenities.airCondition': 'Air Conditioning',
  'amenities.internet': 'Internet',
  'amenities.furnished': 'Furnished',
  'amenities.petFriendly': 'Pet Friendly',
  'amenities.laundry': 'Laundry',
  'amenities.kitchen': 'Kitchen',
  'amenities.terrace': 'Terrace',
  'amenities.seaView': 'Sea View',
};

// Thai translations
const thTranslations = {
  // Navigation
  'nav.search': 'ค้นหา',
  'nav.saved': 'รายการโปรด',
  'nav.list': 'ลงประกาศ',
  'nav.resources': 'ทรัพยากร',
  'nav.messages': 'ข้อความ',
  'nav.profile': 'โปรไฟล์',
  
  // Header
  'header.notifications': 'การแจ้งเตือน',
  'header.logout': 'ออกจากระบบ',
  
  // Common
  'common.loading': 'กำลังโหลด...',
  'common.save': 'บันทึก',
  'common.cancel': 'ยกเลิก',
  'common.delete': 'ลบ',
  'common.edit': 'แก้ไข',
  'common.view': 'ดู',
  'common.close': 'ปิด',
  'common.submit': 'ส่ง',

  // Register/Signup
  'register.title': 'สร้างบัญชี',
  'register.description': 'เข้าร่วม HotProp เพื่อเริ่มซื้อ ขาย หรือเช่าอสังหาริมทรัพย์',
  'register.platformNotice': 'สำคัญ: แพลตฟอร์มเจ้าของกับผู้ซื้อโดยตรง',
  'register.platformDescription': 'HotProp เป็นแพลตฟอร์มสำหรับ <strong>เจ้าของ</strong> อสังหาริมทรัพย์ และผู้ที่ต้องการ <strong>ซื้อหรือเช่า</strong> อสังหาริมทรัพย์เท่านั้น แพลตฟอร์มนี้เชื่อมต่อเจ้าของโดยตรงกับผู้ซื้อและผู้เช่า โดยไม่มีค่านายหน้าหรือค่าคอมมิชชั่น',
  'register.firstName': 'ชื่อจริง',
  'register.lastName': 'นามสกุล',
  'register.email': 'อีเมล',
  'register.phone': 'เบอร์โทรศัพท์ (ไม่บังคับ)',
  'register.password': 'รหัสผ่าน',
  'register.confirmPassword': 'ยืนยันรหัสผ่าน',
  'register.firstNamePlaceholder': 'สมชาย',
  'register.lastNamePlaceholder': 'ใจดี',
  'register.emailPlaceholder': 'somchai@example.com',
  'register.phonePlaceholder': '+66 (xx) xxx-xxxx',
  'register.passwordPlaceholder': 'สร้างรหัสผ่าน',
  'register.confirmPasswordPlaceholder': 'ยืนยันรหัสผ่านของคุณ',
  'register.notAgentConfirm': 'ข้าพเจ้าขอยืนยันว่า ข้าพเจ้า / เรา ไม่ใช่นายหน้าอสังหาริมทรัพย์',
  'register.notAgentRequired': 'จำเป็น: แพลตฟอร์มนี้สำหรับเจ้าของอสังหาริมทรัพย์และผู้ที่ต้องการหาอสังหาริมทรัพย์เท่านั้น',
  'register.agreeTerms': 'ฉันยอมรับ',
  'register.termsOfService': 'ข้อกำหนดการใช้บริการ',
  'register.privacyPolicy': 'นโยบายความเป็นส่วนตัว',
  'register.and': 'และ',
  'register.createAccount': 'สร้างบัญชี',
  'register.creatingAccount': 'กำลังสร้างบัญชี...',
  'register.haveAccount': 'มีบัญชีอยู่แล้ว?',
  'register.signIn': 'เข้าสู่ระบบ',
  'common.search': 'ค้นหา',
  'common.filter': 'กรอง',
  'common.clear': 'ล้าง',
  'common.apply': 'นำไปใช้',
  'common.back': 'กลับ',
  'common.next': 'ถัดไป',
  'common.previous': 'ก่อนหน้า',
  'common.yes': 'ใช่',
  'common.no': 'ไม่',
  'common.ok': 'ตกลง',
  
  // Add Listing
  'addListing.title': 'สร้างประกาศ',
  'addListing.description': 'ลงประกาศขายหรือเช่าอสังหาริมทรัพย์ หรือโพสต์ความต้องการของคุณ',
  'addListing.listProperty': 'ลงประกาศอสังหาฯ',
  'addListing.postRequirement': 'โพสต์ความต้องการ',
  
  // Property Types
  'propertyType.house': 'บ้าน',
  'propertyType.apartment': 'อพาร์ตเมนต์',
  'propertyType.land': 'ที่ดิน',
  'propertyType.townhouse': 'ทาวน์เฮาส์',
  'propertyType.poolvilla': 'บ้านพร้อมสระ',
  
  // Transaction Types
  'transactionType.sell': 'ซื้อ',
  'transactionType.rent': 'เช่า',
  'transactionType.buy': 'ซื้อ',
  'transactionType.sell_or_rent': 'ซื้อและเช่า',
  'transactionType.buy_or_rent': 'ซื้อและเช่า',
  
  // Search
  'search.properties': 'อสังหาริมทรัพย์',
  'search.requirements': 'ความต้องการ',
  'search.noPropertiesFound': 'ไม่พบอสังหาริมทรัพย์',
  'search.noRequirementsFound': 'ไม่พบความต้องการ',
  'search.propertiesFound': 'พบอสังหาริมทรัพย์ {{count}} รายการ',
  'search.requirementsFound': 'พบความต้องการ {{count}} รายการ',
  'search.adjustCriteria': 'ลองปรับเปลี่ยนเงื่อนไขการค้นหา',
  'search.startSearching': 'เริ่มค้นหาอสังหาริมทรัพย์ด้านบน',
  'search.placeholder': 'ค้นหาอสังหาฯ, สถานที่...',
  'search.filterButton': 'กรอง',
  
  // Notifications
  'notifications.title': 'การแจ้งเตือน',
  'notifications.markAllRead': 'ทำเครื่องหมายอ่านทั้งหมด',
  'notifications.noNotifications': 'ไม่มีการแจ้งเตือน',
  'notifications.matches': 'รายการที่เหมาะสมล่าสุด',
  'notifications.newMatches': 'พบรายการใหม่ที่ตรงกับความต้องการของคุณ',
  'notifications.validationReminder': 'กรุณายืนยันว่าประกาศของคุณยังคงพร้อมให้บริการ',
  'notifications.propertyReactivated': 'เปิดใช้งานอสังหาริมทรัพย์เรียบร้อยแล้ว',
  'notifications.requirementReactivated': 'เปิดใช้งานความต้องการเรียบร้อยแล้ว',
  'notifications.failedReactivateProperty': 'ไม่สามารถเปิดใช้งานอสังหาริมทรัพย์ได้',
  'notifications.failedReactivateRequirement': 'ไม่สามารถเปิดใช้งานความต้องการได้',
  
  // Password Reset
  'forgotPassword.linkText': 'ลืมรหัสผ่าน?',
  'forgotPassword.title': 'ลืมรหัสผ่าน',
  'forgotPassword.description': 'กรอกที่อยู่อีเมลและเราจะส่งลิงก์สำหรับรีเซ็ตรหัสผ่านให้คุณ',
  'forgotPassword.email': 'ที่อยู่อีเมล',
  'forgotPassword.emailPlaceholder': 'กรอกที่อยู่อีเมลของคุณ',
  'forgotPassword.sendLink': 'ส่งลิงก์รีเซ็ต',
  'forgotPassword.backToLogin': 'กลับไปเข้าสู่ระบบ',
  'forgotPassword.successMessage': 'หากมีบัญชีที่ใช้อีเมลนี้ คุณจะได้รับอีเมลสำหรับรีเซ็ตรหัสผ่าน',
  'forgotPassword.emailRequired': 'จำเป็นต้องใส่ที่อยู่อีเมล',
  'forgotPassword.sending': 'กำลังส่ง...',
  
  'resetPassword.title': 'รีเซ็ตรหัสผ่าน',
  'resetPassword.description': 'กรอกรหัสผ่านใหม่ของคุณด้านล่าง',
  'resetPassword.newPassword': 'รหัสผ่านใหม่',
  'resetPassword.confirmPassword': 'ยืนยันรหัสผ่านใหม่',
  'resetPassword.newPasswordPlaceholder': 'กรอกรหัสผ่านใหม่',
  'resetPassword.confirmPasswordPlaceholder': 'ยืนยันรหัสผ่านใหม่',
  'resetPassword.resetPassword': 'รีเซ็ตรหัสผ่าน',
  'resetPassword.successMessage': 'รีเซ็ตรหัสผ่านเรียบร้อยแล้ว! ตอนนี้คุณสามารถเข้าสู่ระบบด้วยรหัสผ่านใหม่ได้',
  'resetPassword.invalidToken': 'โทเค็นไม่ถูกต้องหรือหมดอายุแล้ว',
  'resetPassword.passwordRequired': 'จำเป็นต้องใส่รหัสผ่าน',
  'resetPassword.passwordMinLength': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
  'resetPassword.passwordsDoNotMatch': 'รหัสผ่านไม่ตรงกัน',
  'resetPassword.resetting': 'กำลังรีเซ็ต...',
  
  // Common
  'common.success': 'สำเร็จ!',
  'common.error': 'ข้อผิดพลาด',
  
  // Matches
  'matches.title': 'รายการที่เหมาะสมล่าสุด',
  'matches.noMatches': 'ไม่พบรายการที่เหมาะสม',
  'matches.compatibility': 'เหมาะสม {{score}}%',
  'matches.viewDetails': 'ดูรายละเอียด',
  'matches.showingBuyerRequirements': 'แสดงความต้องการของผู้ซื้อ',
  'matches.contactDirectly': 'ผู้ซื้อเหล่านี้กำลังมองหาอสังหาริมทรัพย์ ติดต่อโดยตรงเพื่อหารือโอกาส!',
  
  // Forms
  'form.title': 'หัวข้อ',
  'form.description': 'รายละเอียด',
  'form.price': 'ราคา',
  'form.currency': 'สกุลเงิน',
  'form.bedrooms': 'ห้องนอน',
  'form.bathrooms': 'ห้องน้ำ',
  'property.bedrooms': 'ห้องนอน',
  'property.bathrooms': 'ห้องน้ำ',
  'property.landSize': 'ขนาดที่ดิน',
  'property.buildSize': 'ขนาดอาคาร',
  'property.size': 'ขนาด',
  'property.land': 'ที่ดิน',
  'property.living': 'พื้นที่ใช้สอย',
  'property.forRent': 'ให้เช่า',
  'property.forSale': 'ขาย',
  'form.area': 'พื้นที่',
  'form.city': 'เมือง',
  'form.state': 'จังหวัด',
  'form.country': 'ประเทศ',
  'form.amenities': 'สิ่งอำนวยความสะดวก',
  'form.required': 'จำเป็นต้องกรอกข้อมูลนี้',
  'form.email': 'อีเมล',
  'form.phone': 'โทรศัพท์',
  'form.propertyType': 'ประเภทอสังหาริมทรัพย์',
  'form.transactionType': 'ประเภทการประกาศ',
  'form.listingType': 'ประเภทการประกาศ',
  'form.lookingFor': 'มองหา',
  'form.address': 'ที่อยู่',
  'form.yearBuilt': 'ปีที่สร้าง',
  'form.landSize': 'ขนาดที่ดิน',
  'form.buildSize': 'ขนาดอาคาร',
  'form.purchase': 'ซื้อ',
  'form.rent': 'เช่า',
  'form.rentPrice': 'ราคาเช่า',
  'form.minPrice': 'ราคาต่ำสุด (ไม่บังคับ)',
  'form.maxPrice': 'ราคาสูงสุด (ไม่บังคับ)',
  'form.purchasePriceRange': 'ช่วงราคาซื้อ',
  'form.rentalPriceRange': 'ช่วงราคาเช่า',
  'form.minPurchasePrice': 'ราคาซื้อต่ำสุด',
  'form.maxPurchasePrice': 'ราคาซื้อสูงสุด',
  'form.minRentalPrice': 'ราคาเช่าต่ำสุด',
  'form.maxRentalPrice': 'ราคาเช่าสูงสุด',
  'form.minBedrooms': 'ห้องนอนขั้นต่ำ',
  'form.minBathrooms': 'ห้องน้ำขั้นต่ำ',
  'form.minArea': 'พื้นที่ขั้นต่ำ',
  'form.minLivingArea': 'พื้นที่ใช้สอยขั้นต่ำ',
  'form.minLandArea': 'พื้นที่ที่ดินขั้นต่ำ',
  'form.maxArea': 'พื้นที่สูงสุด',
  'form.urgency': 'ความเร่งด่วน',
  'form.contactEmail': 'อีเมลติดต่อ',
  'form.contactPhone': 'เบอร์โทรติดต่อ',
  'form.areaUnit': 'หน่วยพื้นที่',
  'form.selectType': 'เลือกประเภท',
  'form.selectCurrency': 'เลือกสกุลเงิน',
  'form.selectUnit': 'เลือกหน่วย',
  'form.optional': 'ไม่บังคับ',
  'form.whatLookingFor': 'คุณกำลังมองหาอะไร?',
  'form.describeRequirement': 'อธิบายความต้องการอสังหาริมทรัพย์ในฝันของคุณ',
  'form.salePriceLabel': 'ราคาขาย',
  'form.priceLabel': 'ราคา',
  'form.submit': 'ส่ง',
  'form.update': 'อัปเดต',
  'form.save': 'บันทึกอสังหาริมทรัพย์',
  'form.saveRequirement': 'บันทึกความต้องการ',
  'form.savingListing': 'กรุณารอสักครู่ขณะที่เราบันทึกประกาศของคุณ...',
  'form.addAmenity': 'เพิ่มสิ่งอำนวยความสะดวก',
  'form.addImages': 'เพิ่มรูปภาพ',
  'form.uploadImages': 'อัปโหลดรูปภาพ',
  'form.addMedia': 'เพิ่มรูปภาพและวิดีโอ',
  'form.uploadMedia': 'อัปโหลดรูปภาพและวิดีโอ',
  'form.contactPhoneOptional': 'เบอร์โทรติดต่อ (ไม่บังคับ)',
  'form.contactEmailLabel': 'อีเมลติดต่อ',
  'form.requiredAmenitiesOptional': 'สิ่งอำนวยความสะดวกที่ต้องการ (ไม่บังคับ)',
  'form.selectFromCommonAmenities': 'เลือกจากสิ่งอำนวยความสะดวกทั่วไป',
  'form.landSizeUnit': 'หน่วยขนาดที่ดิน',
  'form.buildSizeUnit': 'หน่วยขนาดอาคาร',
  'form.addNew': 'เพิ่มใหม่',
  'form.images': 'รูปภาพ',
  'form.noImagesUploaded': 'ยังไม่ได้อัปโหลดรูปภาพ',
  'form.uploadingImages': 'กำลังอัปโหลดรูปภาพ...',
  'form.remove': 'ลบ',
  'form.delete': 'ลบ',
  'form.deleting': 'กำลังลบ...',
  
  // Success messages
  'success.propertyDeleted': 'ลบอสังหาริมทรัพย์แล้ว',
  'success.propertyDeletedDesc': 'อสังหาริมทรัพย์ของคุณถูกลบเรียบร้อยแล้ว',
  'success.requirementDeleted': 'ลบความต้องการแล้ว', 
  'success.requirementDeletedDesc': 'ความต้องการของคุณถูกลบเรียบร้อยแล้ว',
  
  // Error messages
  'error.failedToDelete': 'ล้มเหลวในการลบ',
  'error.tryAgain': 'กรุณาลองใหม่อีกครั้ง',
  
  // Confirmation dialogs
  'confirm.deleteProperty': 'ลบอสังหาริมทรัพย์?',
  'confirm.deletePropertyDesc': 'การดำเนินการนี้ไม่สามารถยกเลิกได้ คุณแน่ใจหรือไม่ว่าต้องการลบอสังหาริมทรัพย์นี้อย่างถาวร?',
  'confirm.deleteRequirement': 'ลบความต้องการ?',
  'confirm.deleteRequirementDesc': 'การดำเนินการนี้ไม่สามารถยกเลิกได้ คุณแน่ใจหรือไม่ว่าต้องการลบความต้องการนี้อย่างถาวร?',
  
  // Currencies
  'currency.USD': 'USD ($)',
  'currency.THB': 'THB (฿)',
  
  // Area Units
  'unit.sqm': 'ตารางเมตร',
  'unit.sqw': 'ตารางวา',
  'unit.sqft': 'ตารางฟุต',
  'unit.sqmDetailed': 'ตารางเมตร (sqm)',
  'unit.sqwDetailed': 'ตารางวา (sqw)',
  
  // Urgency
  'urgency.flexible': 'ยืดหยุ่น',
  'urgency.normal': 'ปกติ',
  'urgency.urgent': 'เร่งด่วน',
  
  // Placeholders
  'placeholder.propertyTitle': 'เช่น วิลลา 3 ห้องนอนพร้อมสระว่ายน้ำ',
  'placeholder.requirementTitle': 'เช่น บ้าน 3 ห้องนอนพร้อมสระในตัวเมือง',
  'placeholder.description': 'อธิบายอสังหาริมทรัพย์หรือความต้องการของคุณ...',
  'placeholder.address': 'ที่อยู่',
  'placeholder.city': 'ชื่อเมือง',
  'placeholder.state': 'จังหวัด',
  'placeholder.country': 'ประเทศ',
  'placeholder.email': 'your.email@example.com',
  'placeholder.phone': '+66812345678',
  'placeholder.price': '',
  'placeholder.bedrooms': '',
  'placeholder.bathrooms': '',
  'placeholder.area': '',
  'placeholder.yearBuilt': '',
  'placeholder.emailExample': 'your@email.com',
  'placeholder.phoneExample': '+66 (xx) xxx-xxxx',
  'placeholder.selectUnit': 'เลือกหน่วย',
  'placeholder.selectPropertyType': 'เลือกประเภทอสังหาริมทรัพย์',
  'placeholder.selectListingType': 'เลือกประเภทการลิสต์',
  'placeholder.selectCountry': 'เลือกประเทศ',
  'placeholder.selectState': 'เลือกจังหวัด',
  'placeholder.selectCountryFirst': 'เลือกประเทศก่อน',
  
  
  // Languages
  'language.english': 'English',
  'language.thai': 'ไทย',
  'language.select': 'ภาษา',
  
  // Resources
  'resources.title': 'ทรัพยากร',
  'resources.description': 'ค้นหาบริการสนับสนุนและทรัพยากรที่เป็นประโยชน์',
  'resources.serviceProviders': 'ผู้ให้บริการ',
  'resources.otherResources': 'ทรัพยากรอื่นๆ',
  'resources.serviceCategories': 'หมวดหมู่บริการ',
  'resources.resourceCategories': 'หมวดหมู่ทรัพยากร',
  'resources.allServices': 'บริการทั้งหมด',
  'resources.allResources': 'ทรัพยากรทั้งหมด',
  'resources.noServiceProviders': 'ยังไม่มีผู้ให้บริการ',
  'resources.noResources': 'ยังไม่มีทรัพยากร',
  'resources.contactAdmin': 'ผู้ให้บริการถูกเพิ่มโดยทีมงานของเรา',
  'resources.contactAdminResources': 'ทรัพยากรได้รับการคัดสรรและจัดการโดยทีมแอดมินของเราเท่านั้น',
  'resources.contactUs': 'ติดต่อเรา',
  'resources.serviceAreas': 'พื้นที่ให้บริการ:',
  'resources.email': 'อีเมล',
  'resources.call': 'โทร {{number}}',
  'resources.download': 'ดาวน์โหลด',
  'resources.visit': 'เยี่ยมชม',
  'resources.visitWebsite': 'เยี่ยมชมเว็บไซต์',

  // Help page
  'help.title': 'ต้องการความช่วยเหลือ?',
  'help.subtitle': 'เราพร้อมช่วยเหลือคุณในทุกคำถามหรือปัญหาที่คุณมี',
  'help.contactUs': 'ติดต่อฝ่ายสนับสนุน',
  'help.description': 'เลือกวิธีที่คุณต้องการติดต่อทีมสนับสนุนของเรา',
  'help.inAppMessage': 'ข้อความในแอป',
  'help.sendEmail': 'ส่งอีเมล',
  'help.inAppTitle': 'ส่งข้อความถึงเรา',
  'help.inAppDescription': 'ส่งข้อความโดยตรงผ่านแอป คุณจะได้รับการตอบกลับในข้อความของคุณ',
  'help.yourMessage': 'ข้อความของคุณ',
  'help.messagePlaceholder': 'อธิบายปัญหาหรือคำถามของคุณโดยละเอียด...',
  'help.sending': 'กำลังส่ง...',
  'help.sendMessage': 'ส่งข้อความ',
  'help.emailTitle': 'ส่งอีเมลถึงเรา',
  'help.emailDescription': 'ส่งอีเมลโดยตรงไปยังทีมสนับสนุนของเราที่ applied.skill@gmail.com',
  'help.subject': 'หัวข้อ',
  'help.subjectPlaceholder': 'คำอธิบายสั้นๆ เกี่ยวกับปัญหาของคุณ',
  'help.fromUser': 'จาก',
  'help.faqTitle': 'คำถามที่พบบ่อย',
  'help.faq1Question': 'ฉันจะลิสต์อสังหาริมทรัพย์ได้อย่างไร?',
  'help.faq1Answer': 'คลิกที่ "ลิสต์อสังหาริมทรัพย์" ในเมนูนำทางและกรอกแบบฟอร์มรายละเอียดอสังหาริมทรัพย์',
  'help.faq2Question': 'ฉันจะติดต่อเจ้าของอสังหาริมทรัพย์ได้อย่างไร?',
  'help.faq2Answer': 'คลิกที่รายการอสังหาริมทรัพย์ใดๆ และใช้ปุ่ม "ติดต่อเจ้าของ" เพื่อส่งข้อความโดยตรง',
  'help.faq3Question': 'ความต้องการของผู้ซื้อคืออะไร?',
  'help.faq3Answer': 'ความต้องการของผู้ซื้อช่วยให้คุณระบุประเภทอสังหาริมทรัพย์ที่คุณกำลังมองหา และเราจะแจ้งเตือนคุณเมื่อมีรายการที่ตรงกัน',
  
  // Service categories  
  'serviceCategory.legal': 'บริการกฎหมาย',
  'serviceCategory.legal.description': 'ทำสัญญา กฎหมายอสังหาริมทรัพย์ ฯลฯ',
  'serviceCategory.building': 'บริการก่อสร้าง',
  'serviceCategory.building.description': 'ผู้รับเหมา วัสดุก่อสร้าง ฯลฯ',
  'serviceCategory.architects': 'สถาปนิก',
  'serviceCategory.architects.description': 'การออกแบบและวางแผนทางสถาปัตยกรรม',
  'serviceCategory.interior': 'นักออกแบบตกแต่งภายใน',
  'serviceCategory.interior.description': 'การออกแบบและตกแต่งภายใน',
  'serviceCategory.surveyors': 'ผู้สำรวจ',
  'serviceCategory.surveyors.description': 'การสำรวจที่ดินและอสังหาริมทรัพย์',
  'serviceCategory.handymen': 'ช่างซ่อมบำรุง',
  'serviceCategory.handymen.description': 'ซ่อมแซมและบำรุงรักษาทั่วไป',
  'serviceCategory.pool': 'ผู้ทำความสะอาดสระว่ายน้ำ',
  'serviceCategory.pool.description': 'บำรุงรักษาและทำความสะอาดสระว่ายน้ำ',
  'serviceCategory.garden': 'ผู้ดูแลสวน',
  'serviceCategory.garden.description': 'ดูแลและจัดสวน',
  'serviceCategory.relocation': 'บริการย้ายบ้าน',
  'serviceCategory.relocation.description': 'บริการย้ายและขนส่งของ',
  'serviceCategory.cleaning': 'บริการทำความสะอาด',
  'serviceCategory.cleaning.description': 'บริการทำความสะอาดมืออาชีพ',
  'serviceCategory.photography': 'บริการถ่ายภาพ/วิดีโอมืออาชีพ',
  'serviceCategory.photography.description': 'บริการถ่ายภาพและวิดีโอมืออาชีพ',
  'serviceCategory.other': 'อื่นๆ',
  'serviceCategory.other.description': 'บริการสนับสนุนอื่นๆ',
  
  // Resource categories
  'resourceCategory.documents': 'เอกสารที่มีประโยชน์',
  'resourceCategory.documents.description': 'แม่แบบสัญญาและเอกสารทางกฎหมาย',
  'resourceCategory.links': 'ลิงก์ที่มีประโยชน์',
  'resourceCategory.links.description': 'บริการ AI ทางกฎหมายและทรัพยากรภายนอก',
  
  // Resource documents
  'resource.purchaseAgreement.title': 'แม่แบบสัญญาซื้อขายอสังหาริมทรัพย์',
  'resource.purchaseAgreement.description': 'แม่แบบมาตรฐานสำหรับสัญญาซื้อขายอสังหาริมทรัพย์ในประเทศไทย',
  'resource.rentalContract.title': 'แม่แบบสัญญาเช่า',
  'resource.rentalContract.description': 'แม่แบบสัญญาเช่าครบถ้วนตามข้อกำหนดทางกฎหมายไทย',
  'resource.dueDiligence.title': 'รายการตรวจสอบความถูกต้อง',
  'resource.dueDiligence.description': 'รายการตรวจสอบที่จำเป็นสำหรับผู้ซื้ออสังหาริมทรัพย์เพื่อตรวจสอบสถานะทางกฎหมาย',
  
  // Resource links
  'resource.legalAI.title': 'ผู้ช่วย AI ด้านกฎหมายอสังหาริมทรัพย์',
  'resource.legalAI.description': 'ความช่วยเหลือทางกฎหมายด้วย AI สำหรับคำถามเกี่ยวกับอสังหาริมทรัพย์',
  'resource.landDept.title': 'พอร์ทัลกรมที่ดินไทย',
  'resource.landDept.description': 'พอร์ทัลรัฐบาลอย่างเป็นทางการสำหรับการตรวจสอบโฉนดที่ดิน',
  'resource.taxCalculator.title': 'เครื่องคำนวณภาษีอสังหาริมทรัพย์',
  'resource.taxCalculator.description': 'คำนวณภาษีอสังหาริมทรัพย์และค่าธรรมเนียมการโอน',
  
  // Home page
  'home.premium': 'พรีเมียม',
  'home.premiumDescription': 'เพิ่มโอกาสความสำเร็จ',
  'home.premiumMember': 'สมาชิกพรีเมียม',
  'home.activeSubscription': 'สมาชิกแอ็คทีฟ',
  'home.resources': 'ทรัพยากร',
  'home.resourcesDescription': 'รับบริการสนับสนุน',
  'home.admin': 'แอดมิน',
  'home.adminPanel': 'แผงควบคุมแอดมิน',
  'home.welcomeTitle1': 'ยินดีต้อนรับสู่ HotProp',
  'home.welcomeTitle2': 'ดีลสมาร์ท ค่าธรรมเนียม 0 บาท!',
  'home.welcomeDescription': 'เชื่อมต่อตรงกับเจ้าของอสังหาริมทรัพย์ • ไม่มีค่านายหน้า • ดีลจริง',
  'home.featuredProperties': 'อสังหาริมทรัพย์แนะนำ',
  'home.viewAll': 'ดูทั้งหมด',
  'home.noFeaturedProperties': 'ไม่มีอสังหาริมทรัพย์แนะนำ',

  // Search page
  'search.iWantTo': 'ฉันต้องการ ...',
  'search.buy': 'ซื้อ',
  'search.rent': 'เช่า',
  'search.sell': 'ขาย',
  'search.let': 'ให้เช่า',
  'search.filters': 'ตัวกรองการค้นหา',
  'search.currency': 'สกุลเงิน',
  'search.priceRange': 'ช่วงราคา',
  'search.maxRental': 'ค่าเช่าสูงสุด: {amount}/เดือน',
  'search.maxSalePrice': 'ราคาขายสูงสุด: {amount}',
  'search.bedrooms': 'ห้องนอน',
  'search.bathrooms': 'ห้องน้ำ',
  'search.city': 'เมือง',
  'search.any': 'ทั้งหมด',
  'search.enterCity': 'ป้อนชื่อเมือง',
  'search.applyFilters': 'ใช้ตัวกรอง',
  'search.clear': 'ล้าง',
  'search.clearFilters': 'ล้างตัวกรอง',
  'search.propertyTypes': 'ประเภทอสังหาริมทรัพย์',
  'search.showingBuyerRequirements': '📊 แสดงความต้องการของผู้ซื้อ',
  'search.buyerRequirementsDescription': 'ผู้ซื้อเหล่านี้กำลังมองหาอสังหาริมทรัพย์ ติดต่อพวกเขาโดยตรงเพื่อหารือเกี่ยวกับโอกาส!',
  'search.browseRequirements': 'เรียกดูความต้องการของผู้ซื้อเพื่อหาลูกค้าที่มีศักยภาพ',

  // Property and requirement cards
  'card.deactivated': 'ปิดใช้งาน',
  'card.premium': 'พรีเมียม',
  'card.premiumOwner': 'พรีเมียม',
  'card.verifiedOwner': 'เจ้าของได้รับการยืนยัน',
  'card.noImageAvailable': 'ไม่มีรูปภาพ',
  'card.hoursAgo': '{hours} ชั่วโมงที่แล้ว',
  'card.daysAgo': '{days} วันที่แล้ว',
  'card.upTo': 'สูงสุด',
  'card.from': 'เริ่มต้น',
  'card.bed': 'ห้องนอน',
  'card.bath': 'ห้องน้ำ',
  'card.message': 'ส่งข้อความ',
  'card.call': 'โทร',
  'card.reactivateProperty': 'เปิดใช้งานอสังหาริมทรัพย์',
  'card.reactivating': 'กำลังเปิดใช้งาน...',
  'card.required': 'จำเป็น:',
  'card.more': '+{count} เพิ่มเติม',
  'card.reactivateRequirement': 'เปิดใช้งานความต้องการ',

  // Premium signup page
  'premium.upgradeTitle': 'อัปเกรดเป็นพรีเมียม',
  'premium.premiumMember': 'สมาชิกพรีเมียม',
  'premium.choosePlan': 'เลือกแผนของคุณ',
  'premium.paymentMethod': 'วิธีการชำระเงิน',
  'premium.continueToPayment': 'ดำเนินการชำระเงิน',
  'premium.completePayment': 'ชำระเงินให้เสร็จสิ้น',
  'premium.monthlyPremium': 'พรีเมียมรายเดือน',
  'premium.sixMonthPremium': 'พรีเมียม 6 เดือน',
  'premium.perMonth': 'ต่อเดือน',
  'premium.forSixMonths': 'สำหรับ 6 เดือน',
  'premium.save33': 'ประหยัด 33% เมื่อเทียบกับรายเดือน',
  'premium.moreFeatures': '+{count} ฟีเจอร์เพิ่มเติม',
  'premium.propertyVerification': 'การยืนยันความเป็นเจ้าของอสังหาริมทรัพย์',
  'premium.instantNotifications': 'การแจ้งเตือนแมตช์ทันที (ความเข้ากันได้ 80%+)',
  'premium.priceVisualization': 'การแสดงผลแนวโน้มราคาอัจฉริยะตามย่าน',
  'premium.prioritySupport': 'การสนับสนุนลูกค้าระดับพิเศษ',
  'premium.advancedFilters': 'ตัวกรองการค้นหาขั้นสูง',
  'premium.unlimitedListings': 'ลงประกาศอสังหาฯ และความต้องการได้หลายรายการ',
  'premium.allMonthlyFeatures': 'รวมฟีเจอร์รายเดือนทั้งหมด',
  'premium.bestValue': 'คุ้มค่าที่สุดสำหรับผู้ใช้จริงจัง',
  'premium.promptpayTitle': 'PromptPay / QR Code',
  'premium.promptpayDesc': 'ชำระเงินทันทีด้วยแอปธนาคารมือถือของคุณ',
  'premium.creditCardTitle': 'Visa / MasterCard',
  'premium.creditCardDesc': 'บัตรเครดิตหรือบัตรเดบิต',
  'premium.twoWeeksFree': 'ฟรี 2 สัปดาห์',
  'premium.freeTrialTerms': 'เงื่อนไขการทดลองฟรี:',
  'premium.freeTrialDesc': 'รับสิทธิ์พรีเมียม 2 สัปดาห์ฟรีทั้งหมด! บัตรของคุณจะไม่ถูกเรียกเก็บเงินระหว่างช่วงทดลอง ยกเลิกอย่างน้อย 3 วันก่อนช่วงทดลองสิ้นสุดเพื่อหลีกเลี่ยงการเรียกเก็บเงิน',
  'premium.plan': 'แผน:',
  'premium.amount': 'จำนวน:',
  'premium.trialPeriod': 'ช่วงทดลอง:',
  'premium.creditCardInfo': 'ข้อมูลบัตรเครดิต',
  'premium.processing': 'กำลังประมวลผล...',
  'premium.startFreeTrial': 'เริ่มทดลองฟรี 2 สัปดาห์',
  'premium.payNow': 'จ่ายตอนนี้ ฿{amount}',
  'premium.scanQR': 'สแกน QR Code เพื่อจ่าย',
  'premium.qrInstructions': 'เปิดแอปธนาคารมือถือของคุณและสแกน QR Code นี้เพื่อชำระเงิน',
  'premium.qrExpires': 'QR Code หมดอายุใน:',
  'premium.paymentComplete': 'การชำระเงินเสร็จสมบูรณ์!',
  'premium.activePremium': 'การสมัครสมาชิกพรีเมียมของคุณเปิดใช้งานแล้ว',
  'premium.enjoyingBenefits': 'คุณกำลังเพลิดเพลินกับสิทธิประโยชน์พรีเมียม!',
  'premium.activeSubscription': 'การสมัครสมาชิกใช้งานอยู่',
  'premium.yourPremiumBenefits': 'สิทธิประโยชน์พรีเมียมของคุณ',
  'premium.viewPriceTrends': 'ดูแนวโน้มราคา',
  'premium.viewNotifications': 'ดูการแจ้งเตือน',
  'premium.cancelSubscription': 'ยกเลิกการสมัครสมาชิก',
  
  // Toast messages
  'premium.toast.selectPaymentMethod': 'โปรดเลือกวิธีการชำระเงิน',
  'premium.toast.selectPaymentDesc': 'เลือกระหว่าง PromptPay/QR Code หรือบัตรเครดิตเพื่อดำเนินการต่อ',
  'premium.toast.promptPaySuccess': 'เริ่มการชำระเงิน PromptPay แล้ว',
  'premium.toast.promptPaySuccessDesc': 'โปรดดำเนินการชำระเงินผ่านแอปธนาคารมือถือของคุณ',
  'premium.toast.paymentFailed': 'การชำระเงินล้มเหลว',
  'premium.toast.paymentFailedDesc': 'โปรดลองอีกครั้งหรือติดต่อฝ่ายสนับสนุน',
  'premium.toast.paymentSetupFailed': 'การตั้งค่าการชำระเงินล้มเหลว',
  'premium.toast.welcomeToPremium': 'ยินดีต้อนรับสู่พรีเมียม!',
  'premium.toast.welcomeDesc': 'ตอนนี้คุณมีสิทธิ์พรีเมียมฟรี 2 สัปดาห์ คุณจะถูกเรียกเก็บเงินหลังจากช่วงทดลองสิ้นสุดเท่านั้น เว้นแต่คุณจะยกเลิก',
  'premium.toast.subscriptionSetupFailed': 'การตั้งค่าการสมัครสมาชิกล้มเหลว',
  'premium.toast.contactSupport': 'โปรดติดต่อฝ่ายสนับสนุน',
  'premium.toast.subscriptionCancelled': 'ยกเลิกการสมัครสมาชิกแล้ว',
  'premium.toast.downgradedDesc': 'คุณถูกปรับลดระดับเป็นสมาชิกทั่วไปแล้ว สิทธิ์พรีเมียมของคุณจะยังคงใช้ได้จนถึงสิ้นสุดรอบบิลปัจจุบัน',
  'premium.toast.downgradeFailed': 'การปรับลดระดับล้มเหลว',
  
  // QR modal additional keys
  'premium.instructions': 'คำแนะนำ:',
  'premium.confirmPayment': 'ยืนยันการชำระเงิน',
  'premium.activateAccess': 'สิทธิ์พรีเมียมของคุณจะเปิดใช้งาน',
  'premium.promptpayPayment': 'การชำระเงิน PromptPay',
  'premium.generateQRCode': 'สร้าง QR Code',
  'premium.setUpPayment': 'ตั้งค่าการชำระเงิน',
  'premium.paymentId': 'รหัสการชำระเงิน:',
  
  // Messages page
  'messages.title': 'ข้อความ',
  'messages.searchConversations': 'ค้นหาการสนทนา...',
  'messages.noConversations': 'ยังไม่มีการสนทนา',
  'messages.startMessaging': 'เริ่มส่งข้อความกับเจ้าของอสังหาริมทรัพย์หรือผู้ซื้อ',
  'messages.propertyInquiry': 'สอบถามอสังหาริมทรัพย์',
  'messages.generalMessage': 'ข้อความทั่วไป',
  'messages.property': 'อสังหาริมทรัพย์',
  'messages.message': 'ข้อความ',
  'messages.inactive': 'ไม่ใช้งาน',
  'messages.conversation': 'การสนทนา',
  'messages.typeMessage': 'พิมพ์ข้อความของคุณ...',
  'messages.new': 'ใหม่',
  'messages.unknownUser': 'ผู้ใช้ไม่ทราบชื่อ',
  'messages.failedToSend': 'ส่งข้อความไม่สำเร็จ',
  
  // Notifications page - additional to existing
  'notifications.new': 'ใหม่',
  'notifications.allCaughtUp': 'คุณได้ดูครบทุกอันแล้ว! การแจ้งเตือนใหม่จะปรากฏที่นี่',
  'notifications.reactivate': 'เปิดใช้งาน',
  'notifications.reactivating': 'กำลังเปิดใช้งาน...',
  'notifications.success': 'สำเร็จ!',
  'notifications.error': 'ข้อผิดพลาด',
  'notifications.reactivated': 'เปิดใช้งานสำเร็จแล้ว',
  'notifications.markedAsRead': 'ทำเครื่องหมายการแจ้งเตือนว่าอ่านแล้ว',
  'notifications.allMarkedAsRead': 'ทำเครื่องหมายการแจ้งเตือนทั้งหมดว่าอ่านแล้ว',
  'notifications.deleted': 'ลบการแจ้งเตือนแล้ว',
  'notifications.failedMarkAsRead': 'ไม่สามารถทำเครื่องหมายการแจ้งเตือนว่าอ่านแล้ว',
  'notifications.failedMarkAllAsRead': 'ไม่สามารถทำเครื่องหมายการแจ้งเตือนทั้งหมดว่าอ่านแล้ว',
  'notifications.failedDelete': 'ไม่สามารถลบการแจ้งเตือน',
  'notifications.minAgo': '{minutes} นาทีที่แล้ว',
  'notifications.hourAgo': '{hours} ชั่วโมงที่แล้ว',
  'notifications.dayAgo': '{days} วันที่แล้ว',
  
  // Profile page
  'profile.premium': 'พรีเมียม',
  'profile.free': 'ฟรี',
  'profile.verified': 'ยืนยันแล้ว',
  'profile.editProfile': 'แก้ไขโปรไฟล์',
  'profile.logout': 'ออกจากระบบ',
  'profile.listings': 'ประกาศ',
  'profile.saved': 'บันทึกไว้',
  'profile.requests': 'ความต้องการ',
  'profile.upgradeToPremium': 'อัปเกรดเป็นพรีเมียม',
  'profile.upgradeDescription': 'รับประกาศพรีเมียม การแจ้งเตือน และอื่นๆ',
  'profile.upgrade': 'อัปเกรด',
  'profile.getVerified': 'รับการยืนยัน',
  'profile.getVerifiedDescription': 'ยืนยันความเป็นเจ้าของอสังหาริมทรัพย์ของคุณ',
  'profile.verificationBenefits': 'โดดเด่นให้ผู้ซื้อเห็นด้วยสถานะความเป็นเจ้าของที่ได้รับการยืนยัน',
  'profile.verificationPending': 'การยืนยันกำลังดำเนินการ',
  'profile.verificationPendingDesc': 'เอกสารการยืนยันของคุณกำลังได้รับการตรวจสอบ',
  'profile.verificationRejected': 'การยืนยันถูกปฏิเสธ',
  'profile.verificationRejectedDesc': 'กรุณาส่งเอกสารใหม่เพื่อการยืนยัน',
  'profile.myProperties': 'อสังหาริมทรัพย์ของฉัน',
  'profile.savedProperties': 'อสังหาริมทรัพย์ที่บันทึกไว้',
  'profile.myRequirements': 'ความต้องการของฉัน',
  'profile.myListings': 'ประกาศของฉัน',
  'profile.addNew': 'เพิ่มใหม่',
  'profile.noPropertiesYet': 'คุณยังไม่ได้ลงประกาศอสังหาริมทรัพย์',
  'profile.createFirstListing': 'สร้างประกาศแรกของคุณ',
  'profile.noSavedYet': 'คุณยังไม่ได้บันทึกอสังหาริมทรัพย์ไว้',
  'profile.browseProperties': 'เรียกดูอสังหาริมทรัพย์',
  'profile.noRequirementsYet': 'คุณยังไม่ได้โพสต์ความต้องการ',
  'profile.postFirstRequirement': 'โพสต์ความต้องการแรกของคุณ',
  
  // Edit Profile page
  'editProfile.title': 'แก้ไขโปรไฟล์',
  'editProfile.firstName': 'ชื่อจริง',
  'editProfile.lastName': 'นามสกุล',
  'editProfile.phoneNumber': 'เบอร์โทรศัพท์',
  'editProfile.firstNamePlaceholder': 'ใส่ชื่อจริงของคุณ',
  'editProfile.lastNamePlaceholder': 'ใส่นามสกุลของคุณ',
  'editProfile.phonePlaceholder': 'ใส่เบอร์โทรศัพท์ของคุณ',
  'editProfile.cancel': 'ยกเลิก',
  'editProfile.saveChanges': 'บันทึกการเปลี่ยนแปลง',
  'editProfile.saving': 'กำลังบันทึก...',
  'editProfile.firstNameRequired': 'ต้องระบุชื่อจริง',
  'editProfile.lastNameRequired': 'ต้องระบุนามสกุล',
  'editProfile.profileUpdated': 'อัปเดตโปรไฟล์แล้ว',
  'editProfile.profileUpdatedDesc': 'โปรไฟล์ของคุณได้รับการอัปเดตเรียบร้อยแล้ว',
  'editProfile.updateFailed': 'อัปเดตไม่สำเร็จ',
  
  // Favorites page
  'favorites.title': 'อสังหาริมทรัพย์ที่บันทึกไว้',
  'favorites.subtitle': 'อสังหาริมทรัพย์ที่คุณได้บุ๊กมาร์กไว้',
  'favorites.noSavedTitle': 'ไม่มีอสังหาริมทรัพย์ที่บันทึกไว้',
  'favorites.noSavedDescription': 'เริ่มเรียกดูและบันทึกอสังหาริมทรัพย์ที่คุณสนใจ',
  
  // Premium page
  'premium.featuresTitle': 'ฟีเจอร์พรีเมียม',
  'premium.creditCardPayment': 'การชำระเงินด้วยบัตรเครดิต',
  'premium.securePaymentSetup': 'คลิกปุ่มด้านล่างเพื่อตั้งค่าการชำระเงินที่ปลอดภัย',
  'premium.payWithPromptPay': 'ชำระด้วย PromptPay',
  'premium.close': 'ปิด',
  
  // Login page
  'login.welcomeBack': 'ยินดีต้อนรับกลับมา',
  'login.signInToContinue': 'เข้าสู่ระบบเพื่อดำเนินการต่อ',
  'login.email': 'อีเมล',
  'login.emailPlaceholder': 'กรุณาใส่อีเมลของคุณ',
  'login.password': 'รหัสผ่าน',
  'login.passwordPlaceholder': 'กรุณาใส่รหัสผ่านของคุณ',
  'login.signIn': 'เข้าสู่ระบบ',
  'login.signingIn': 'กำลังเข้าสู่ระบบ...',
  'login.noAccount': 'ยังไม่มีบัญชี?',
  'login.signUp': 'สมัครสมาชิก',
  'login.termsAndPrivacy': 'การเข้าสู่ระบบหมายความว่าคุณยอมรับข้อกำหนดการให้บริการและนโยบายความเป็นส่วนตัวของเรา',
  'login.emailNotVerified': 'อีเมลยังไม่ได้รับการยืนยัน',
  'login.resendVerificationText': 'คุณต้องยืนยันอีเมลก่อนจึงจะเข้าสู่ระบบได้',
  'login.resendVerification': 'ส่งอีเมลยืนยัน',
  'login.sendingVerification': 'กำลังส่ง...',
  'login.cancelResend': 'ยกเลิก',
  
  // Property Details
  'propertyDetails.description': 'รายละเอียดอสังหาริมทรัพย์',
  'propertyDetails.amenities': 'สิ่งอำนวยความสะดวก',
  'propertyDetails.details': 'รายละเอียดอสังหาริมทรัพย์',
  'propertyDetails.listedBy': 'ลงประกาศโดยเจ้าของ',
  'propertyDetails.propertyType': 'ประเภทอสังหาริมทรัพย์',
  'propertyDetails.yearBuilt': 'ปีที่สร้าง',
  'propertyDetails.listed': 'ลงประกาศ',
  'propertyDetails.reportListing': 'รายงานประกาศนี้',
  'propertyDetails.rating': 'คะแนน',
  'propertyDetails.call': 'โทร',
  'propertyDetails.email': 'อีเมล',
  'propertyDetails.sendMessage': 'ส่งข้อความ',
  'propertyDetails.share': 'แชร์',
  'propertyDetails.back': 'กลับ',
  'propertyDetails.addToFavorites': 'เพิ่มในรายการโปรด',
  'propertyDetails.removeFromFavorites': 'ลบออกจากรายการโปรด',
  
  // Amenities (comprehensive list from database)
  'amenity.carPark': 'ที่จอดรถ',
  'amenity.doubleCarPark': 'ที่จอดรถคู่',
  'amenity.coveredCarPark': 'ที่จอดรถมีหลังคา',
  'amenity.garden': 'สวน',
  'amenity.childrenPlayground': 'สนามเด็กเล่น',
  'amenity.communalPool': 'สระว่ายน้ำส่วนกลาง',
  'amenity.privatePool': 'สระว่ายน้ำส่วนตัว',
  'amenity.poolSpecific': 'สระว่ายน้ำ 6x3 เมตร',
  'amenity.sauna': 'ซาวน่า',
  'amenity.gym': 'ฟิตเนส',
  'amenity.nearBeach': 'ใกล้ชายหาด',
  'amenity.nearSchool': 'ใกล้โรงเรียน',
  'amenity.nearHospital': 'ใกล้โรงพยาบาล',
  'amenity.nearRestaurants': 'ใกล้ร้านอาหาร',
  'amenity.nearConvenience': 'ใกล้ร้านสะดวกซื้อ',
  'amenity.quietLocation': 'ทำเลเงียบ',
  'amenity.seaView': 'วิวทะเล',
  'amenity.balconyWithSeaview': 'ระเบียงวิวทะเล',
  'amenity.mountainView': 'วิวภูเขา',
  'amenity.lakeView': 'วิวทะเลสาบ',
  'amenity.gardenView': 'วิวสวน',
  'amenity.balcony': 'ระเบียง',
  'amenity.rooftopTerrace': 'ดาดฟ้า',
  'amenity.petsOk': 'เลี้ยงสัตว์ได้',
  'amenity.laundryFacilities': 'ห้องซักผ้า',
  'amenity.internetWifi': 'อินเทอร์เน็ต/WiFi',
  'amenity.security24h': 'รปภ. 24 ชม.',
  'amenity.openChimney': 'เตาผิงเปิด',
  'amenity.privateBar': 'บาร์ส่วนตัว',
  'amenity.fullyFurnished': 'เฟอร์นิเจอร์ครบ',
  
  // Form instructions
  'form.numbersOnly': '(ใส่เฉพาะตัวเลข)',
  
  // Premium Welcome Page
  'premium.welcomeTitle': 'ขอบคุณมากสำหรับการอัพเกรดเป็นสมาชิกพรีเมียม',
  'premium.welcomeMessage': 'ประกาศของคุณจะได้รับความสำคัญสูงขึ้น คุณสามารถลงประกาศอสังหาฯ หรือความต้องการได้มากกว่าหนึ่งรายการ และคุณจะได้รับสิทธิประโยชน์อื่นๆ ของสมาชิกพรีเมียม (เราจะเพิ่มสิทธิประโยชน์เพิ่มเติมต่อไป)',
  'premium.backToHome': 'กลับสู่หน้าหลัก',
  
  // Premium restrictions
  'premium.multipleListingsRequired': 'ต้องเป็นสมาชิกพรีเมียมเพื่อลงประกาศอสังหาฯ ได้หลายรายการ กรุณาอัพเกรดเพื่อดำเนินการต่อ',
  'premium.multipleRequirementsRequired': 'ต้องเป็นสมาชิกพรีเมียมเพื่อโพสต์ความต้องการได้หลายรายการ กรุณาอัพเกรดเพื่อดำเนินการต่อ',
};

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    // Get language from localStorage or default to English
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('hotprop-language');
      return (stored as Language) || 'en';
    }
    return 'en';
  });

  // Save language preference to localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('hotprop-language', language);
    }
  }, [language]);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
  };

  const translate = (key: string, params?: Record<string, string | number>): string => {
    return t(language, key, params);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t: translate }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}