// Location data with English and Thai translations
// Thailand is listed first as requested

export interface Country {
  code: string;
  nameEn: string;
  nameTh: string;
  states: State[];
}

export interface State {
  code: string;
  nameEn: string;
  nameTh: string;
}

export const locationData: Country[] = [
  // Thailand first as requested
  {
    code: "TH",
    nameEn: "Thailand",
    nameTh: "ประเทศไทย",
    states: [
      { code: "TH-10", nameEn: "Bangkok", nameTh: "กรุงเทพมหานคร" },
      { code: "TH-50", nameEn: "Chiang Mai", nameTh: "เชียงใหม่" },
      { code: "TH-57", nameEn: "Chiang Rai", nameTh: "เชียงราย" },
      { code: "TH-20", nameEn: "Chonburi", nameTh: "ชลบุรี" },
      { code: "TH-86", nameEn: "Chumphon", nameTh: "ชุมพร" },
      { code: "TH-46", nameEn: "Kalasin", nameTh: "กาฬสินธุ์" },
      { code: "TH-62", nameEn: "Kamphaeng Phet", nameTh: "กำแพงเพชร" },
      { code: "TH-71", nameEn: "Kanchanaburi", nameTh: "กาญจนบุรี" },
      { code: "TH-40", nameEn: "Khon Kaen", nameTh: "ขอนแก่น" },
      { code: "TH-81", nameEn: "Krabi", nameTh: "กระบี่" },
      { code: "TH-52", nameEn: "Lampang", nameTh: "ลำปาง" },
      { code: "TH-51", nameEn: "Lamphun", nameTh: "ลำพูน" },
      { code: "TH-42", nameEn: "Loei", nameTh: "เลย" },
      { code: "TH-16", nameEn: "Lopburi", nameTh: "ลพบุรี" },
      { code: "TH-58", nameEn: "Mae Hong Son", nameTh: "แม่ฮ่องสอน" },
      { code: "TH-44", nameEn: "Maha Sarakham", nameTh: "มหาสารคาม" },
      { code: "TH-49", nameEn: "Mukdahan", nameTh: "มุกดาหาร" },
      { code: "TH-26", nameEn: "Nakhon Nayok", nameTh: "นครนายก" },
      { code: "TH-73", nameEn: "Nakhon Pathom", nameTh: "นครปฐม" },
      { code: "TH-48", nameEn: "Nakhon Phanom", nameTh: "นครพนม" },
      { code: "TH-30", nameEn: "Nakhon Ratchasima", nameTh: "นครราชสีมา" },
      { code: "TH-80", nameEn: "Nakhon Si Thammarat", nameTh: "นครศรีธรรมราช" },
      { code: "TH-55", nameEn: "Nan", nameTh: "น่าน" },
      { code: "TH-96", nameEn: "Narathiwat", nameTh: "นราธิวาส" },
      { code: "TH-39", nameEn: "Nong Bua Lam Phu", nameTh: "หนองบัวลำภู" },
      { code: "TH-43", nameEn: "Nong Khai", nameTh: "หนองคาย" },
      { code: "TH-12", nameEn: "Nonthaburi", nameTh: "นนทบุรี" },
      { code: "TH-13", nameEn: "Pathum Thani", nameTh: "ปทุมธานี" },
      { code: "TH-94", nameEn: "Pattani", nameTh: "ปัตตานี" },
      { code: "TH-82", nameEn: "Phang Nga", nameTh: "พังงา" },
      { code: "TH-93", nameEn: "Phatthalung", nameTh: "พัทลุง" },
      { code: "TH-56", nameEn: "Phayao", nameTh: "พะเยา" },
      { code: "TH-67", nameEn: "Phetchabun", nameTh: "เพชรบูรณ์" },
      { code: "TH-76", nameEn: "Phetchaburi", nameTh: "เพชรบุรี" },
      { code: "TH-66", nameEn: "Phichit", nameTh: "พิจิตร" },
      { code: "TH-65", nameEn: "Phitsanulok", nameTh: "พิษณุโลก" },
      { code: "TH-54", nameEn: "Phrae", nameTh: "แพร่" },
      { code: "TH-83", nameEn: "Phuket", nameTh: "ภูเก็ต" },
      { code: "TH-25", nameEn: "Prachin Buri", nameTh: "ปราจีนบุรี" },
      { code: "TH-77", nameEn: "Prachuap Khiri Khan", nameTh: "ประจวบคีรีขันธ์" },
      { code: "TH-85", nameEn: "Ranong", nameTh: "ระนอง" },
      { code: "TH-70", nameEn: "Ratchaburi", nameTh: "ราชบุรี" },
      { code: "TH-21", nameEn: "Rayong", nameTh: "ระยอง" },
      { code: "TH-45", nameEn: "Roi Et", nameTh: "ร้อยเอ็ด" },
      { code: "TH-27", nameEn: "Sa Kaeo", nameTh: "สระแก้ว" },
      { code: "TH-47", nameEn: "Sakon Nakhon", nameTh: "สกลนคร" },
      { code: "TH-11", nameEn: "Samut Prakan", nameTh: "สมุทรปราการ" },
      { code: "TH-74", nameEn: "Samut Sakhon", nameTh: "สมุทรสาคร" },
      { code: "TH-75", nameEn: "Samut Songkhram", nameTh: "สมุทรสงคราม" },
      { code: "TH-19", nameEn: "Saraburi", nameTh: "สระบุรี" },
      { code: "TH-91", nameEn: "Satun", nameTh: "สตูล" },
      { code: "TH-17", nameEn: "Sing Buri", nameTh: "สิงห์บุรี" },
      { code: "TH-33", nameEn: "Sisaket", nameTh: "ศรีสะเกษ" },
      { code: "TH-90", nameEn: "Songkhla", nameTh: "สงขลา" },
      { code: "TH-64", nameEn: "Sukhothai", nameTh: "สุโขทัย" },
      { code: "TH-72", nameEn: "Suphan Buri", nameTh: "สุพรรณบุรี" },
      { code: "TH-84", nameEn: "Surat Thani", nameTh: "สุราษฎร์ธานี" },
      { code: "TH-32", nameEn: "Surin", nameTh: "สุรินทร์" },
      { code: "TH-63", nameEn: "Tak", nameTh: "ตาก" },
      { code: "TH-92", nameEn: "Trang", nameTh: "ตรัง" },
      { code: "TH-23", nameEn: "Trat", nameTh: "ตราด" },
      { code: "TH-34", nameEn: "Ubon Ratchathani", nameTh: "อุบลราชธานี" },
      { code: "TH-41", nameEn: "Udon Thani", nameTh: "อุดรธานี" },
      { code: "TH-61", nameEn: "Uthai Thani", nameTh: "อุทัยธานี" },
      { code: "TH-53", nameEn: "Uttaradit", nameTh: "อุตรดิตถ์" },
      { code: "TH-95", nameEn: "Yala", nameTh: "ยะลา" },
      { code: "TH-35", nameEn: "Yasothon", nameTh: "ยโสธร" }
    ]
  },
  // Other countries alphabetically
  {
    code: "AU",
    nameEn: "Australia",
    nameTh: "ออสเตรเลีย",
    states: [
      { code: "ACT", nameEn: "Australian Capital Territory", nameTh: "เขตเมืองหลวงออสเตรเลีย" },
      { code: "NSW", nameEn: "New South Wales", nameTh: "นิวเซาท์เวลส์" },
      { code: "NT", nameEn: "Northern Territory", nameTh: "นอร์เทิร์นเทร์ริทอรี" },
      { code: "QLD", nameEn: "Queensland", nameTh: "ควีนส์แลนด์" },
      { code: "SA", nameEn: "South Australia", nameTh: "เซาท์ออสเตรเลีย" },
      { code: "TAS", nameEn: "Tasmania", nameTh: "แทสเมเนีย" },
      { code: "VIC", nameEn: "Victoria", nameTh: "วิคตอเรีย" },
      { code: "WA", nameEn: "Western Australia", nameTh: "เวสเทิร์นออสเตรเลีย" }
    ]
  },
  {
    code: "CA",
    nameEn: "Canada",
    nameTh: "แคนาดา",
    states: [
      { code: "AB", nameEn: "Alberta", nameTh: "แอลเบอร์ตา" },
      { code: "BC", nameEn: "British Columbia", nameTh: "บริติชโคลัมเบีย" },
      { code: "MB", nameEn: "Manitoba", nameTh: "แมนิโทบา" },
      { code: "NB", nameEn: "New Brunswick", nameTh: "นิวบรันสวิก" },
      { code: "NL", nameEn: "Newfoundland and Labrador", nameTh: "นิวฟันด์แลนด์และแลบราดอร์" },
      { code: "NS", nameEn: "Nova Scotia", nameTh: "โนวาสโกเชีย" },
      { code: "NT", nameEn: "Northwest Territories", nameTh: "นอร์ธเวสต์เทร์ริทอรีส์" },
      { code: "NU", nameEn: "Nunavut", nameTh: "นูนาวุต" },
      { code: "ON", nameEn: "Ontario", nameTh: "ออนแทรีโอ" },
      { code: "PE", nameEn: "Prince Edward Island", nameTh: "เจ้าชายเอ็ดเวิร์ดไอส์แลนด์" },
      { code: "QC", nameEn: "Quebec", nameTh: "ควิเบก" },
      { code: "SK", nameEn: "Saskatchewan", nameTh: "ซัสแคตเชวัน" },
      { code: "YT", nameEn: "Yukon", nameTh: "ยูคอน" }
    ]
  },
  {
    code: "CN",
    nameEn: "China",
    nameTh: "จีน",
    states: [
      { code: "BJ", nameEn: "Beijing", nameTh: "ปักกิ่ง" },
      { code: "TJ", nameEn: "Tianjin", nameTh: "เทียนจิน" },
      { code: "HE", nameEn: "Hebei", nameTh: "เหอเป่ย" },
      { code: "SX", nameEn: "Shanxi", nameTh: "ซานซี" },
      { code: "NM", nameEn: "Inner Mongolia", nameTh: "มองโกเลียใน" },
      { code: "LN", nameEn: "Liaoning", nameTh: "เหลียวหนิง" },
      { code: "JL", nameEn: "Jilin", nameTh: "จี๋หลิน" },
      { code: "HL", nameEn: "Heilongjiang", nameTh: "เฮยหลงเจียง" },
      { code: "SH", nameEn: "Shanghai", nameTh: "เซี่ยงไฮ้" },
      { code: "JS", nameEn: "Jiangsu", nameTh: "เจียงซู" },
      { code: "ZJ", nameEn: "Zhejiang", nameTh: "เจ้อเจียง" },
      { code: "AH", nameEn: "Anhui", nameTh: "อันฮุย" },
      { code: "FJ", nameEn: "Fujian", nameTh: "ฝูเจี้ยน" },
      { code: "JX", nameEn: "Jiangxi", nameTh: "เจียงซี" },
      { code: "SD", nameEn: "Shandong", nameTh: "ซานตง" },
      { code: "HA", nameEn: "Henan", nameTh: "เหอหนาน" },
      { code: "HB", nameEn: "Hubei", nameTh: "หูเป่ย" },
      { code: "HN", nameEn: "Hunan", nameTh: "หูหนาน" },
      { code: "GD", nameEn: "Guangdong", nameTh: "กวางตง" },
      { code: "GX", nameEn: "Guangxi", nameTh: "กวางซี" },
      { code: "HI", nameEn: "Hainan", nameTh: "ไหหนาน" },
      { code: "CQ", nameEn: "Chongqing", nameTh: "ฉงชิ่ง" },
      { code: "SC", nameEn: "Sichuan", nameTh: "เสฉวน" },
      { code: "GZ", nameEn: "Guizhou", nameTh: "กุ้ยโจว" },
      { code: "YN", nameEn: "Yunnan", nameTh: "ยูนนาน" },
      { code: "XZ", nameEn: "Tibet", nameTh: "ทิเบต" },
      { code: "SN", nameEn: "Shaanxi", nameTh: "ส่านซี" },
      { code: "GS", nameEn: "Gansu", nameTh: "กานซู" },
      { code: "QH", nameEn: "Qinghai", nameTh: "ชิงไห่" },
      { code: "NX", nameEn: "Ningxia", nameTh: "หนิงเซี่ย" },
      { code: "XJ", nameEn: "Xinjiang", nameTh: "ซินเจียง" },
      { code: "HK", nameEn: "Hong Kong", nameTh: "ฮ่องกง" },
      { code: "MO", nameEn: "Macau", nameTh: "มาเก๊า" }
    ]
  },
  {
    code: "FR",
    nameEn: "France",
    nameTh: "ฝรั่งเศส",
    states: [
      { code: "ARA", nameEn: "Auvergne-Rhône-Alpes", nameTh: "โอแวร์นย์-โรน-แอลป์" },
      { code: "BFC", nameEn: "Bourgogne-Franche-Comté", nameTh: "บูร์กอญ-ฟร็องซ์-กง-เต" },
      { code: "BRE", nameEn: "Brittany", nameTh: "เบรอตาญ" },
      { code: "CVL", nameEn: "Centre-Val de Loire", nameTh: "เซ็นต์เตอร์-วัล เดอ ลัวร์" },
      { code: "COR", nameEn: "Corsica", nameTh: "คอร์ซิกา" },
      { code: "GES", nameEn: "Grand Est", nameTh: "กรองด์ เอสต์" },
      { code: "HDF", nameEn: "Hauts-de-France", nameTh: "โอต์-เดอ-ฝรั่งเศส" },
      { code: "IDF", nameEn: "Île-de-France", nameTh: "อีล-เดอ-ฝรั่งเศส" },
      { code: "NOR", nameEn: "Normandy", nameTh: "นอร์มังดี" },
      { code: "NAQ", nameEn: "Nouvelle-Aquitaine", nameTh: "นูแวล-อาแก็ตเตน" },
      { code: "OCC", nameEn: "Occitania", nameTh: "อ็อกซิตานี" },
      { code: "PDL", nameEn: "Pays de la Loire", nameTh: "เปอี เดอ ลา ลัวร์" },
      { code: "PAC", nameEn: "Provence-Alpes-Côte d'Azur", nameTh: "โพรวองซ์-แอลป์-โกต ดาซูร์" }
    ]
  },
  {
    code: "DE",
    nameEn: "Germany",
    nameTh: "เยอรมนี",
    states: [
      { code: "BW", nameEn: "Baden-Württemberg", nameTh: "บาเดิน-เวือร์เทมแบร์ก" },
      { code: "BY", nameEn: "Bavaria", nameTh: "บาวาเรีย" },
      { code: "BE", nameEn: "Berlin", nameTh: "เบอร์ลิน" },
      { code: "BB", nameEn: "Brandenburg", nameTh: "บรานเดนบูร์ก" },
      { code: "HB", nameEn: "Bremen", nameTh: "เบรเมิน" },
      { code: "HH", nameEn: "Hamburg", nameTh: "ฮัมบูร์ก" },
      { code: "HE", nameEn: "Hesse", nameTh: "เฮสเซิน" },
      { code: "MV", nameEn: "Mecklenburg-Vorpommern", nameTh: "เมคเคลนบูร์ก-ฟอร์พอมเมิร์น" },
      { code: "NI", nameEn: "Lower Saxony", nameTh: "โลเวอร์แซกโซนี" },
      { code: "NW", nameEn: "North Rhine-Westphalia", nameTh: "นอร์ธไรน์-เวสต์ฟาเลีย" },
      { code: "RP", nameEn: "Rhineland-Palatinate", nameTh: "ไรน์แลนด์-พาลาทิเนต" },
      { code: "SL", nameEn: "Saarland", nameTh: "ซาร์ลันด์" },
      { code: "SN", nameEn: "Saxony", nameTh: "แซกโซนี" },
      { code: "ST", nameEn: "Saxony-Anhalt", nameTh: "แซกโซนี-อันฮัลต์" },
      { code: "SH", nameEn: "Schleswig-Holstein", nameTh: "ชเลสวิก-โฮลไสน์" },
      { code: "TH", nameEn: "Thuringia", nameTh: "ทูรินเกีย" }
    ]
  },
  {
    code: "IN",
    nameEn: "India",
    nameTh: "อินเดีย",
    states: [
      { code: "AP", nameEn: "Andhra Pradesh", nameTh: "อานธรประเทศ" },
      { code: "AR", nameEn: "Arunachal Pradesh", nameTh: "อรุณาจลประเทศ" },
      { code: "AS", nameEn: "Assam", nameTh: "อัสสัม" },
      { code: "BR", nameEn: "Bihar", nameTh: "พิหาร" },
      { code: "CG", nameEn: "Chhattisgarh", nameTh: "ชัตติสครห์" },
      { code: "GA", nameEn: "Goa", nameTh: "โกอา" },
      { code: "GJ", nameEn: "Gujarat", nameTh: "คุชราต" },
      { code: "HR", nameEn: "Haryana", nameTh: "หริยานา" },
      { code: "HP", nameEn: "Himachal Pradesh", nameTh: "หิมาจลประเทศ" },
      { code: "JK", nameEn: "Jammu and Kashmir", nameTh: "จัมมูและแคชเมียร์" },
      { code: "JH", nameEn: "Jharkhand", nameTh: "ยารขันด์" },
      { code: "KA", nameEn: "Karnataka", nameTh: "กรณาฏกะ" },
      { code: "KL", nameEn: "Kerala", nameTh: "เกรละ" },
      { code: "MP", nameEn: "Madhya Pradesh", nameTh: "มัธยประเทศ" },
      { code: "MH", nameEn: "Maharashtra", nameTh: "มหาราษฏระ" },
      { code: "MN", nameEn: "Manipur", nameTh: "มณีปุระ" },
      { code: "ML", nameEn: "Meghalaya", nameTh: "เมฆาลยะ" },
      { code: "MZ", nameEn: "Mizoram", nameTh: "มิโซรัม" },
      { code: "NL", nameEn: "Nagaland", nameTh: "นาคาแลนด์" },
      { code: "OR", nameEn: "Odisha", nameTh: "โอฑิศา" },
      { code: "PB", nameEn: "Punjab", nameTh: "ปัญจาบ" },
      { code: "RJ", nameEn: "Rajasthan", nameTh: "ราชสถาน" },
      { code: "SK", nameEn: "Sikkim", nameTh: "สิกขิม" },
      { code: "TN", nameEn: "Tamil Nadu", nameTh: "ทมิฬนาฑู" },
      { code: "TS", nameEn: "Telangana", nameTh: "เตลังคานา" },
      { code: "TR", nameEn: "Tripura", nameTh: "ตริปุระ" },
      { code: "UP", nameEn: "Uttar Pradesh", nameTh: "อุตตรประเทศ" },
      { code: "UK", nameEn: "Uttarakhand", nameTh: "อุตตราขันด์" },
      { code: "WB", nameEn: "West Bengal", nameTh: "เบงคอลตะวันตก" },
      { code: "DL", nameEn: "Delhi", nameTh: "เดลี" }
    ]
  },
  {
    code: "ID",
    nameEn: "Indonesia",
    nameTh: "อินโดนีเซีย",
    states: [
      { code: "AC", nameEn: "Aceh", nameTh: "อาเจะห์" },
      { code: "SU", nameEn: "North Sumatra", nameTh: "สุมาตราเหนือ" },
      { code: "SB", nameEn: "West Sumatra", nameTh: "สุมาตราตะวันตก" },
      { code: "RI", nameEn: "Riau", nameTh: "เรียว" },
      { code: "JA", nameEn: "Jambi", nameTh: "จัมบี" },
      { code: "SS", nameEn: "South Sumatra", nameTh: "สุมาตราใต้" },
      { code: "BE", nameEn: "Bengkulu", nameTh: "เบงกูลู" },
      { code: "LA", nameEn: "Lampung", nameTh: "ลัมปุง" },
      { code: "BB", nameEn: "Bangka Belitung", nameTh: "บังกา-เบลิตุง" },
      { code: "KR", nameEn: "Kepulauan Riau", nameTh: "หมู่เกาะเรียว" },
      { code: "JK", nameEn: "Jakarta", nameTh: "จาการ์ตา" },
      { code: "JB", nameEn: "West Java", nameTh: "ชวาตะวันตก" },
      { code: "JT", nameEn: "Central Java", nameTh: "ชวากลาง" },
      { code: "YO", nameEn: "Yogyakarta", nameTh: "ยอกยาการ์ตา" },
      { code: "JI", nameEn: "East Java", nameTh: "ชวาตะวันออก" },
      { code: "BT", nameEn: "Banten", nameTh: "บันเตน" },
      { code: "BA", nameEn: "Bali", nameTh: "บาหลี" },
      { code: "NB", nameEn: "West Nusa Tenggara", nameTh: "นูซาเตงการาตะวันตก" },
      { code: "NT", nameEn: "East Nusa Tenggara", nameTh: "นูซาเตงการาตะวันออก" },
      { code: "KB", nameEn: "West Kalimantan", nameTh: "กาลิมันตันตะวันตก" },
      { code: "KT", nameEn: "Central Kalimantan", nameTh: "กาลิมันตันกลาง" },
      { code: "KS", nameEn: "South Kalimantan", nameTh: "กาลิมันตันใต้" },
      { code: "KI", nameEn: "East Kalimantan", nameTh: "กาลิมันตันตะวันออก" },
      { code: "KU", nameEn: "North Kalimantan", nameTh: "กาลิมันตันเหนือ" },
      { code: "SA", nameEn: "North Sulawesi", nameTh: "สุลาเวสีเหนือ" },
      { code: "ST", nameEn: "Central Sulawesi", nameTh: "สุลาเวสีกลาง" },
      { code: "SN", nameEn: "South Sulawesi", nameTh: "สุลาเวสีใต้" },
      { code: "SG", nameEn: "Southeast Sulawesi", nameTh: "สุลาเวสีตะวันออกเฉียงใต้" },
      { code: "GO", nameEn: "Gorontalo", nameTh: "โกรอนตาโล" },
      { code: "SR", nameEn: "West Sulawesi", nameTh: "สุลาเวสีตะวันตก" },
      { code: "MA", nameEn: "Maluku", nameTh: "มาลูกู" },
      { code: "MU", nameEn: "North Maluku", nameTh: "มาลูกูเหนือ" },
      { code: "PA", nameEn: "Papua", nameTh: "ปาปัว" },
      { code: "PB", nameEn: "West Papua", nameTh: "ปาปัวตะวันตก" }
    ]
  },
  {
    code: "JP",
    nameEn: "Japan",
    nameTh: "ญี่ปุ่น",
    states: [
      { code: "01", nameEn: "Hokkaido", nameTh: "ฮอกไกโด" },
      { code: "02", nameEn: "Aomori", nameTh: "อาโอโมริ" },
      { code: "03", nameEn: "Iwate", nameTh: "อิวาเตะ" },
      { code: "04", nameEn: "Miyagi", nameTh: "มิยางิ" },
      { code: "05", nameEn: "Akita", nameTh: "อากิตะ" },
      { code: "06", nameEn: "Yamagata", nameTh: "ยามากาตะ" },
      { code: "07", nameEn: "Fukushima", nameTh: "ฟุกุชิมะ" },
      { code: "08", nameEn: "Ibaraki", nameTh: "อิบารากิ" },
      { code: "09", nameEn: "Tochigi", nameTh: "โทชิงิ" },
      { code: "10", nameEn: "Gunma", nameTh: "กุนมะ" },
      { code: "11", nameEn: "Saitama", nameTh: "ไซตามะ" },
      { code: "12", nameEn: "Chiba", nameTh: "ชิบะ" },
      { code: "13", nameEn: "Tokyo", nameTh: "โตเกียว" },
      { code: "14", nameEn: "Kanagawa", nameTh: "คานากาวะ" },
      { code: "15", nameEn: "Niigata", nameTh: "นีงาตะ" },
      { code: "16", nameEn: "Toyama", nameTh: "โทยามะ" },
      { code: "17", nameEn: "Ishikawa", nameTh: "อิชิกาวะ" },
      { code: "18", nameEn: "Fukui", nameTh: "ฟุกุอิ" },
      { code: "19", nameEn: "Yamanashi", nameTh: "ยามานาชิ" },
      { code: "20", nameEn: "Nagano", nameTh: "นางาโนะ" },
      { code: "21", nameEn: "Gifu", nameTh: "งิฟุ" },
      { code: "22", nameEn: "Shizuoka", nameTh: "ชิซุโอกะ" },
      { code: "23", nameEn: "Aichi", nameTh: "ไอจิ" },
      { code: "24", nameEn: "Mie", nameTh: "มิเอะ" },
      { code: "25", nameEn: "Shiga", nameTh: "ชิงะ" },
      { code: "26", nameEn: "Kyoto", nameTh: "เกียวโต" },
      { code: "27", nameEn: "Osaka", nameTh: "โอซากะ" },
      { code: "28", nameEn: "Hyogo", nameTh: "เฮียวโกะ" },
      { code: "29", nameEn: "Nara", nameTh: "นาระ" },
      { code: "30", nameEn: "Wakayama", nameTh: "วากายามะ" },
      { code: "31", nameEn: "Tottori", nameTh: "ทอตโตริ" },
      { code: "32", nameEn: "Shimane", nameTh: "ชิมาเนะ" },
      { code: "33", nameEn: "Okayama", nameTh: "โอกายามะ" },
      { code: "34", nameEn: "Hiroshima", nameTh: "ฮิโรชิมะ" },
      { code: "35", nameEn: "Yamaguchi", nameTh: "ยามากุจิ" },
      { code: "36", nameEn: "Tokushima", nameTh: "โทกุชิมะ" },
      { code: "37", nameEn: "Kagawa", nameTh: "คางาวะ" },
      { code: "38", nameEn: "Ehime", nameTh: "เอฮิเมะ" },
      { code: "39", nameEn: "Kochi", nameTh: "โคจิ" },
      { code: "40", nameEn: "Fukuoka", nameTh: "ฟุกุโอกะ" },
      { code: "41", nameEn: "Saga", nameTh: "ซางะ" },
      { code: "42", nameEn: "Nagasaki", nameTh: "นางาซากิ" },
      { code: "43", nameEn: "Kumamoto", nameTh: "คุมาโมโตะ" },
      { code: "44", nameEn: "Oita", nameTh: "โออิตะ" },
      { code: "45", nameEn: "Miyazaki", nameTh: "มิยาซากิ" },
      { code: "46", nameEn: "Kagoshima", nameTh: "คาโงชิมะ" },
      { code: "47", nameEn: "Okinawa", nameTh: "โอกินาวะ" }
    ]
  },
  {
    code: "MY",
    nameEn: "Malaysia",
    nameTh: "มาเลเซีย",
    states: [
      { code: "JHR", nameEn: "Johor", nameTh: "ยะโฮร์" },
      { code: "KDH", nameEn: "Kedah", nameTh: "เกดาห์" },
      { code: "KTN", nameEn: "Kelantan", nameTh: "กลันตัน" },
      { code: "KUL", nameEn: "Kuala Lumpur", nameTh: "กัวลาลัมเปอร์" },
      { code: "LBN", nameEn: "Labuan", nameTh: "ลาบวน" },
      { code: "MLK", nameEn: "Melaka", nameTh: "มะละกา" },
      { code: "NSN", nameEn: "Negeri Sembilan", nameTh: "นักรีเซมบีลัน" },
      { code: "PHG", nameEn: "Pahang", nameTh: "ปาหัง" },
      { code: "PRK", nameEn: "Perak", nameTh: "ปีรัก" },
      { code: "PLS", nameEn: "Perlis", nameTh: "ปัลลิส" },
      { code: "PNG", nameEn: "Penang", nameTh: "ปีนัง" },
      { code: "PJY", nameEn: "Putrajaya", nameTh: "ปุตราจายา" },
      { code: "SBH", nameEn: "Sabah", nameTh: "ซาบาห์" },
      { code: "SWK", nameEn: "Sarawak", nameTh: "ซาราวัก" },
      { code: "SGR", nameEn: "Selangor", nameTh: "เซลังงอร์" },
      { code: "TRG", nameEn: "Terengganu", nameTh: "ตรังกานู" }
    ]
  },
  {
    code: "PH",
    nameEn: "Philippines",
    nameTh: "ฟิลิปปินส์",
    states: [
      { code: "ABR", nameEn: "Abra", nameTh: "อับรา" },
      { code: "AGN", nameEn: "Agusan del Norte", nameTh: "อากุซันเดลนอร์เต" },
      { code: "AGS", nameEn: "Agusan del Sur", nameTh: "อากุซันเดลซูร์" },
      { code: "AKL", nameEn: "Aklan", nameTh: "อักลาน" },
      { code: "ALB", nameEn: "Albay", nameTh: "อัลไบ" },
      { code: "ANT", nameEn: "Antique", nameTh: "อันติเก" },
      { code: "APA", nameEn: "Apayao", nameTh: "อาปาเยา" },
      { code: "AUR", nameEn: "Aurora", nameTh: "เอาโรรา" },
      { code: "BAS", nameEn: "Basilan", nameTh: "บาซิลาน" },
      { code: "BAN", nameEn: "Bataan", nameTh: "บาตาอัน" },
      { code: "BTN", nameEn: "Batanes", nameTh: "บาตาเนส" },
      { code: "BTG", nameEn: "Batangas", nameTh: "บาตังกัส" },
      { code: "BEN", nameEn: "Benguet", nameTh: "เบนเกต" },
      { code: "BIL", nameEn: "Biliran", nameTh: "บิลิรัน" },
      { code: "BOH", nameEn: "Bohol", nameTh: "โบฮอล" },
      { code: "BUK", nameEn: "Bukidnon", nameTh: "บูกิดนอน" },
      { code: "BUL", nameEn: "Bulacan", nameTh: "บูลาคาน" },
      { code: "CAG", nameEn: "Cagayan", nameTh: "คากายัน" },
      { code: "CAN", nameEn: "Camarines Norte", nameTh: "คามารีเนสนอร์เต" },
      { code: "CAS", nameEn: "Camarines Sur", nameTh: "คามารีเนสซูร์" },
      { code: "CAM", nameEn: "Camiguin", nameTh: "คามิกิน" },
      { code: "CAP", nameEn: "Capiz", nameTh: "คาปิซ" },
      { code: "CAT", nameEn: "Catanduanes", nameTh: "คาตันดวนเนส" },
      { code: "CAV", nameEn: "Cavite", nameTh: "คาวีเต" },
      { code: "CEB", nameEn: "Cebu", nameTh: "เซบู" },
      { code: "COM", nameEn: "Compostela Valley", nameTh: "คอมโปสเตลาวัลเลย์" },
      { code: "NCO", nameEn: "Cotabato", nameTh: "โคตาบาโต" },
      { code: "DAV", nameEn: "Davao del Norte", nameTh: "ดาเวาเดลนอร์เต" },
      { code: "DAS", nameEn: "Davao del Sur", nameTh: "ดาเวาเดลซูร์" },
      { code: "DAC", nameEn: "Davao Occidental", nameTh: "ดาเวาออกซิเดนตัล" },
      { code: "DAO", nameEn: "Davao Oriental", nameTh: "ดาเวาโอเรียนตัล" },
      { code: "DIN", nameEn: "Dinagat Islands", nameTh: "หมู่เกาะดินากัต" },
      { code: "EAS", nameEn: "Eastern Samar", nameTh: "ซามาร์ตะวันออก" },
      { code: "GUI", nameEn: "Guimaras", nameTh: "กีมาราส" },
      { code: "IFU", nameEn: "Ifugao", nameTh: "อิฟูเกา" },
      { code: "ILN", nameEn: "Ilocos Norte", nameTh: "อิโลคอสนอร์เต" },
      { code: "ILS", nameEn: "Ilocos Sur", nameTh: "อิโลคอสซูร์" },
      { code: "ILI", nameEn: "Iloilo", nameTh: "อิโลอิโล" },
      { code: "ISA", nameEn: "Isabela", nameTh: "อิซาเบลา" },
      { code: "KAL", nameEn: "Kalinga", nameTh: "คาลิงกา" },
      { code: "LUN", nameEn: "La Union", nameTh: "ลาอูนิออน" },
      { code: "LAG", nameEn: "Laguna", nameTh: "ลากูนา" },
      { code: "LAN", nameEn: "Lanao del Norte", nameTh: "ลานาเวาเดลนอร์เต" },
      { code: "LAS", nameEn: "Lanao del Sur", nameTh: "ลานาเวาเดลซูร์" },
      { code: "LEY", nameEn: "Leyte", nameTh: "เลย์เต" },
      { code: "MAG", nameEn: "Maguindanao", nameTh: "มากินดานาโอ" },
      { code: "MAR", nameEn: "Marinduque", nameTh: "มารินดูเก" },
      { code: "MAS", nameEn: "Masbate", nameTh: "มาสบาเต" },
      { code: "MSC", nameEn: "Misamis Occidental", nameTh: "มิซามิสออกซิเดนตัล" },
      { code: "MSR", nameEn: "Misamis Oriental", nameTh: "มิซามิสโอเรียนตัล" },
      { code: "MOU", nameEn: "Mountain Province", nameTh: "เมาน์เทนโปรวินซ์" },
      { code: "NEC", nameEn: "Negros Occidental", nameTh: "เนกรอสออกซิเดนตัล" },
      { code: "NER", nameEn: "Negros Oriental", nameTh: "เนกรอสโอเรียนตัล" },
      { code: "NSA", nameEn: "Northern Samar", nameTh: "ซามาร์เหนือ" },
      { code: "NUE", nameEn: "Nueva Ecija", nameTh: "นูเอวาเอซีจา" },
      { code: "NUV", nameEn: "Nueva Vizcaya", nameTh: "นูเอวาวิสกายา" },
      { code: "MDC", nameEn: "Occidental Mindoro", nameTh: "มินโดโรออกซิเดนตัล" },
      { code: "MDR", nameEn: "Oriental Mindoro", nameTh: "มินโดโรโอเรียนตัล" },
      { code: "PLW", nameEn: "Palawan", nameTh: "ปาลาวัน" },
      { code: "PAM", nameEn: "Pampanga", nameTh: "ปัมปังกา" },
      { code: "PAN", nameEn: "Pangasinan", nameTh: "ปังกาซินาน" },
      { code: "QUE", nameEn: "Quezon", nameTh: "เกซอน" },
      { code: "QUI", nameEn: "Quirino", nameTh: "กีรีโน" },
      { code: "RIZ", nameEn: "Rizal", nameTh: "รีซัล" },
      { code: "ROM", nameEn: "Romblon", nameTh: "รอมบลอน" },
      { code: "WSA", nameEn: "Samar", nameTh: "ซามาร์" },
      { code: "SAR", nameEn: "Sarangani", nameTh: "ซารันกานี" },
      { code: "SIQ", nameEn: "Siquijor", nameTh: "ซิกีฮอร์" },
      { code: "SOR", nameEn: "Sorsogon", nameTh: "โซร์โซกอน" },
      { code: "SCO", nameEn: "South Cotabato", nameTh: "เซาท์โคตาบาโต" },
      { code: "SLE", nameEn: "Southern Leyte", nameTh: "เซาเทิร์นเลย์เต" },
      { code: "SUK", nameEn: "Sultan Kudarat", nameTh: "สุลต่านกุดารัต" },
      { code: "SLU", nameEn: "Sulu", nameTh: "ซูลู" },
      { code: "SUN", nameEn: "Surigao del Norte", nameTh: "ซูรีเกาเดลนอร์เต" },
      { code: "SUR", nameEn: "Surigao del Sur", nameTh: "ซูรีเกาเดลซูร์" },
      { code: "TAR", nameEn: "Tarlac", nameTh: "ตาร์ลัก" },
      { code: "TAW", nameEn: "Tawi-Tawi", nameTh: "ตาวี-ตาวี" },
      { code: "ZMB", nameEn: "Zambales", nameTh: "ซัมบาเลส" },
      { code: "ZAN", nameEn: "Zamboanga del Norte", nameTh: "ซัมโบอังกาเดลนอร์เต" },
      { code: "ZAS", nameEn: "Zamboanga del Sur", nameTh: "ซัมโบอังกาเดลซูร์" },
      { code: "ZSI", nameEn: "Zamboanga Sibugay", nameTh: "ซัมโบอังกาซิบูไก" },
      { code: "00", nameEn: "Metro Manila", nameTh: "มหานครมนิลา" }
    ]
  },
  {
    code: "SG",
    nameEn: "Singapore",
    nameTh: "สิงคโปร์",
    states: [
      { code: "SG", nameEn: "Singapore", nameTh: "สิงคโปร์" }
    ]
  },
  {
    code: "KR",
    nameEn: "South Korea",
    nameTh: "เกาหลีใต้",
    states: [
      { code: "11", nameEn: "Seoul", nameTh: "โซล" },
      { code: "26", nameEn: "Busan", nameTh: "ปูซาน" },
      { code: "27", nameEn: "Daegu", nameTh: "แทกู" },
      { code: "30", nameEn: "Daejeon", nameTh: "แทจอน" },
      { code: "29", nameEn: "Gwangju", nameTh: "กวางจู" },
      { code: "28", nameEn: "Incheon", nameTh: "อินชอน" },
      { code: "31", nameEn: "Ulsan", nameTh: "อุลซาน" },
      { code: "43", nameEn: "North Chungcheong", nameTh: "ชุงชองเหนือ" },
      { code: "44", nameEn: "South Chungcheong", nameTh: "ชุงชองใต้" },
      { code: "42", nameEn: "Gangwon", nameTh: "คังวอน" },
      { code: "41", nameEn: "Gyeonggi", nameTh: "เคียงกี" },
      { code: "47", nameEn: "North Gyeongsang", nameTh: "เคียงซังเหนือ" },
      { code: "48", nameEn: "South Gyeongsang", nameTh: "เคียงซังใต้" },
      { code: "49", nameEn: "Jeju", nameTh: "เชจู" },
      { code: "45", nameEn: "North Jeolla", nameTh: "ชอลลาเหนือ" },
      { code: "46", nameEn: "South Jeolla", nameTh: "ชอลลาใต้" }
    ]
  },
  {
    code: "GB",
    nameEn: "United Kingdom",
    nameTh: "สหราชอาณาจักร",
    states: [
      { code: "ENG", nameEn: "England", nameTh: "อังกฤษ" },
      { code: "SCT", nameEn: "Scotland", nameTh: "สกอตแลนด์" },
      { code: "WLS", nameEn: "Wales", nameTh: "เวลส์" },
      { code: "NIR", nameEn: "Northern Ireland", nameTh: "ไอร์แลนด์เหนือ" }
    ]
  },
  {
    code: "US",
    nameEn: "United States",
    nameTh: "สหรัฐอเมริกา",
    states: [
      { code: "AL", nameEn: "Alabama", nameTh: "อลาบามา" },
      { code: "AK", nameEn: "Alaska", nameTh: "อลาสกา" },
      { code: "AZ", nameEn: "Arizona", nameTh: "อริโซนา" },
      { code: "AR", nameEn: "Arkansas", nameTh: "อาร์คันซอ" },
      { code: "CA", nameEn: "California", nameTh: "แคลิฟอร์เนีย" },
      { code: "CO", nameEn: "Colorado", nameTh: "โคโลราโด" },
      { code: "CT", nameEn: "Connecticut", nameTh: "คอนเนตทิคัต" },
      { code: "DE", nameEn: "Delaware", nameTh: "เดลาแวร์" },
      { code: "FL", nameEn: "Florida", nameTh: "ฟลอริดา" },
      { code: "GA", nameEn: "Georgia", nameTh: "จอร์เจีย" },
      { code: "HI", nameEn: "Hawaii", nameTh: "ฮาวาย" },
      { code: "ID", nameEn: "Idaho", nameTh: "ไอดาโฮ" },
      { code: "IL", nameEn: "Illinois", nameTh: "อิลลินอยส์" },
      { code: "IN", nameEn: "Indiana", nameTh: "อินดีแอนา" },
      { code: "IA", nameEn: "Iowa", nameTh: "ไอโอวา" },
      { code: "KS", nameEn: "Kansas", nameTh: "แคนซัส" },
      { code: "KY", nameEn: "Kentucky", nameTh: "เคนตักกี้" },
      { code: "LA", nameEn: "Louisiana", nameTh: "ลุยเซียนา" },
      { code: "ME", nameEn: "Maine", nameTh: "เมน" },
      { code: "MD", nameEn: "Maryland", nameTh: "แมรี่แลนด์" },
      { code: "MA", nameEn: "Massachusetts", nameTh: "แมสซาชูเซตส์" },
      { code: "MI", nameEn: "Michigan", nameTh: "มิชิแกน" },
      { code: "MN", nameEn: "Minnesota", nameTh: "มินนิโซตา" },
      { code: "MS", nameEn: "Mississippi", nameTh: "มิสซิสซิปปี้" },
      { code: "MO", nameEn: "Missouri", nameTh: "มิสซูรี่" },
      { code: "MT", nameEn: "Montana", nameTh: "มอนตานา" },
      { code: "NE", nameEn: "Nebraska", nameTh: "เนบราสกา" },
      { code: "NV", nameEn: "Nevada", nameTh: "เนวาดา" },
      { code: "NH", nameEn: "New Hampshire", nameTh: "นิวแฮมป์เชียร์" },
      { code: "NJ", nameEn: "New Jersey", nameTh: "นิวเจอร์ซีย์" },
      { code: "NM", nameEn: "New Mexico", nameTh: "นิวเม็กซิโก" },
      { code: "NY", nameEn: "New York", nameTh: "นิวยอร์ก" },
      { code: "NC", nameEn: "North Carolina", nameTh: "นอร์ธแคโรไลนา" },
      { code: "ND", nameEn: "North Dakota", nameTh: "นอร์ธดาโกตา" },
      { code: "OH", nameEn: "Ohio", nameTh: "โอไฮโอ" },
      { code: "OK", nameEn: "Oklahoma", nameTh: "โอคลาโฮมา" },
      { code: "OR", nameEn: "Oregon", nameTh: "โอเรกอน" },
      { code: "PA", nameEn: "Pennsylvania", nameTh: "เพนซิลเวเนีย" },
      { code: "RI", nameEn: "Rhode Island", nameTh: "โรดไอแลนด์" },
      { code: "SC", nameEn: "South Carolina", nameTh: "เซาท์แคโรไลนา" },
      { code: "SD", nameEn: "South Dakota", nameTh: "เซาท์ดาโกตา" },
      { code: "TN", nameEn: "Tennessee", nameTh: "เทนเนสซี" },
      { code: "TX", nameEn: "Texas", nameTh: "เท็กซัส" },
      { code: "UT", nameEn: "Utah", nameTh: "ยูทาห์" },
      { code: "VT", nameEn: "Vermont", nameTh: "เวอร์มอนต์" },
      { code: "VA", nameEn: "Virginia", nameTh: "เวอร์จีเนีย" },
      { code: "WA", nameEn: "Washington", nameTh: "วอชิงตัน" },
      { code: "WV", nameEn: "West Virginia", nameTh: "เวสต์เวอร์จีเนีย" },
      { code: "WI", nameEn: "Wisconsin", nameTh: "วิสคอนซิน" },
      { code: "WY", nameEn: "Wyoming", nameTh: "ไวโอมิง" },
      { code: "DC", nameEn: "District of Columbia", nameTh: "ดิสทริกต์ออฟโคลัมเบีย" }
    ]
  },
  {
    code: "VN",
    nameEn: "Vietnam",
    nameTh: "เวียดนาม",
    states: [
      { code: "AN", nameEn: "An Giang", nameTh: "อานยาง" },
      { code: "BA", nameEn: "Ba Ria-Vung Tau", nameTh: "บาเรีย-หวุงเต่า" },
      { code: "BK", nameEn: "Bac Kan", nameTh: "บั๊กกาน" },
      { code: "BL", nameEn: "Bac Lieu", nameTh: "บั๊กเลียว" },
      { code: "BN", nameEn: "Bac Ninh", nameTh: "บั๊กนิง" },
      { code: "BG", nameEn: "Ben Tre", nameTh: "เบนเจ" },
      { code: "BH", nameEn: "Binh Dinh", nameTh: "บิงดิง" },
      { code: "BU", nameEn: "Binh Duong", nameTh: "บิงเซือง" },
      { code: "BP", nameEn: "Binh Phuoc", nameTh: "บิงฟึก" },
      { code: "BT", nameEn: "Binh Thuan", nameTh: "บิงถวน" },
      { code: "CM", nameEn: "Ca Mau", nameTh: "กะเมา" },
      { code: "CT", nameEn: "Can Tho", nameTh: "กานโธ่" },
      { code: "CB", nameEn: "Cao Bang", nameTh: "เก่าบั่ง" },
      { code: "DT", nameEn: "Dak Lak", nameTh: "ดักลัก" },
      { code: "DN", nameEn: "Dak Nong", nameTh: "ดักนง" },
      { code: "DN2", nameEn: "Da Nang", nameTh: "ดานัง" },
      { code: "DB", nameEn: "Dien Bien", nameTh: "เดียนเบียน" },
      { code: "DL", nameEn: "Dong Nai", nameTh: "ดองใน" },
      { code: "DT2", nameEn: "Dong Thap", nameTh: "ดองทับ" },
      { code: "GL", nameEn: "Gia Lai", nameTh: "ยาไล" },
      { code: "HB", nameEn: "Ha Giang", nameTh: "ฮาเยียง" },
      { code: "HD", nameEn: "Hai Duong", nameTh: "ไฮเซือง" },
      { code: "HP", nameEn: "Hai Phong", nameTh: "ไฮฟอง" },
      { code: "HM", nameEn: "Ha Nam", nameTh: "ฮานาม" },
      { code: "HN", nameEn: "Hanoi", nameTh: "ฮานอย" },
      { code: "HT", nameEn: "Ha Tinh", nameTh: "ฮาติง" },
      { code: "HG", nameEn: "Hau Giang", nameTh: "เหิ่วเยียง" },
      { code: "HCM", nameEn: "Ho Chi Minh City", nameTh: "นครโฮจิมินห์" },
      { code: "HB2", nameEn: "Hoa Binh", nameTh: "หวาบิง" },
      { code: "HY", nameEn: "Hung Yen", nameTh: "หึงเอียน" },
      { code: "KH", nameEn: "Khanh Hoa", nameTh: "คั่งหวา" },
      { code: "KG", nameEn: "Kien Giang", nameTh: "เกียนเยียง" },
      { code: "KT", nameEn: "Kon Tum", nameTh: "กอนตุม" },
      { code: "LC", nameEn: "Lai Chau", nameTh: "ไลโจว" },
      { code: "LD", nameEn: "Lam Dong", nameTh: "ลัมดง" },
      { code: "LS", nameEn: "Lang Son", nameTh: "ลางเซิน" },
      { code: "LC2", nameEn: "Lao Cai", nameTh: "เหลาไก่" },
      { code: "LG", nameEn: "Long An", nameTh: "ลองอาน" },
      { code: "ND", nameEn: "Nam Dinh", nameTh: "นามดิง" },
      { code: "NA", nameEn: "Nghe An", nameTh: "งเอ" },
      { code: "NB", nameEn: "Ninh Binh", nameTh: "นิงบิง" },
      { code: "NT", nameEn: "Ninh Thuan", nameTh: "นิงถวน" },
      { code: "PT", nameEn: "Phu Tho", nameTh: "ฟูโท" },
      { code: "PY", nameEn: "Phu Yen", nameTh: "ฟูเอียน" },
      { code: "QB", nameEn: "Quang Binh", nameTh: "ก๋วางบิง" },
      { code: "QN", nameEn: "Quang Nam", nameTh: "ก๋วางนาม" },
      { code: "QG", nameEn: "Quang Ngai", nameTh: "ก๋วางไง" },
      { code: "QN2", nameEn: "Quang Ninh", nameTh: "ก๋วางนิง" },
      { code: "QT", nameEn: "Quang Tri", nameTh: "ก๋วางตรี" },
      { code: "ST", nameEn: "Soc Trang", nameTh: "โซกจาง" },
      { code: "SL", nameEn: "Son La", nameTh: "เซินลา" },
      { code: "TN", nameEn: "Tay Ninh", nameTh: "ตายนิง" },
      { code: "TB", nameEn: "Thai Binh", nameTh: "ไทบิง" },
      { code: "TN2", nameEn: "Thai Nguyen", nameTh: "ไทเงวียน" },
      { code: "TH", nameEn: "Thanh Hoa", nameTh: "ถ่านหวา" },
      { code: "HU", nameEn: "Thua Thien Hue", nameTh: "ถัวเทียนฮื้อ" },
      { code: "TG", nameEn: "Tien Giang", nameTh: "เทียนเยียง" },
      { code: "TV", nameEn: "Tra Vinh", nameTh: "จาวิง" },
      { code: "TQ", nameEn: "Tuyen Quang", nameTh: "ตุเยนก๋วาง" },
      { code: "VL", nameEn: "Vinh Long", nameTh: "วิงลง" },
      { code: "VP", nameEn: "Vinh Phuc", nameTh: "วิงฟุก" },
      { code: "YB", nameEn: "Yen Bai", nameTh: "เอียนใบ" }
    ]
  }
];

// Utility functions to get data in specific language
export const getCountries = (language: 'en' | 'th' = 'en') => {
  return locationData.map(country => ({
    code: country.code,
    name: language === 'th' ? country.nameTh : country.nameEn
  }));
};

export const getStates = (countryCode: string, language: 'en' | 'th' = 'en') => {
  const country = locationData.find(c => c.code === countryCode);
  if (!country) return [];
  
  return country.states.map(state => ({
    code: state.code,
    name: language === 'th' ? state.nameTh : state.nameEn
  }));
};

export const getCountryName = (countryCode: string, language: 'en' | 'th' = 'en') => {
  const country = locationData.find(c => c.code === countryCode);
  if (!country) return countryCode;
  return language === 'th' ? country.nameTh : country.nameEn;
};

export const getStateName = (countryCode: string, stateCode: string, language: 'en' | 'th' = 'en') => {
  const country = locationData.find(c => c.code === countryCode);
  if (!country) return stateCode;
  
  const state = country.states.find(s => s.code === stateCode);
  if (!state) return stateCode;
  
  return language === 'th' ? state.nameTh : state.nameEn;
};